Repository ManageIQ/manageiq-v2v, pull requests merged in 2018-04, with the labels that each got.

#171 Migration nav item should not have any sub items & should show what's currently in Overview
  app/javascript/components/index.js
  app/javascript/react/config/Toolbar.js
  app/javascript/react/config/config.js
  app/javascript/react/screens/App/InfrastructureMappings/InfrastructureMappings.js
  lib/miq_v2v_ui/engine.rb
Labels: enhancement

#181 Updates no breaking deps
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/OverviewActions.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/MappingWizardClusterStepActions.test.js.snap
  package.json
  yarn.lock
Labels: p3, sprint6

#221 Adds parent datacenter to cluster name in infrastructure mapping wizard
  app/javascript/components/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/DualPaneMapper/DualPaneMapperListItem.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepReducer.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/MappingWizardClustersStepReducers.test.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/MappingWizardClustersStepReducers.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/__tests__/__snapshots__/helpers.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/clustersStepForm.fixtures.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/mappingWizardClustersStep.fixtures.js
Labels: enhancement, p1, sprint7

#225 Make entire migration in progress card clickable
  app/javascript/react/config/Routes.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/Overview.scss
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCards.js
Labels: enhancement, sprint7

#226 Reset pagination when adding a filter
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList.js
Labels: p2, sprint7

#238 Migration plan to fully use empty state pattern
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/CSVDropzoneField.js
Labels: needs-prioritization, sprint7

#241 VMs List View
  app/javascript/components/index.js
  app/javascript/react/screens/App/Overview/Overview.scss
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsNotStartedList.test.js
  app/javascript/react/screens/App/Plan/Plan.js
  app/javascript/react/screens/App/Plan/PlanActions.js
  app/javascript/react/screens/App/Plan/PlanConstants.js
  app/javascript/react/screens/App/Plan/PlanReducer.js
  app/javascript/react/screens/App/Plan/__test__/PlanActions.test.js
  app/javascript/react/screens/App/Plan/__test__/PlanReducer.test.js
  app/javascript/react/screens/App/Plan/__test__/__snapshots__/PlanActions.test.js.snap
  app/javascript/react/screens/App/Plan/components/PlanVmsList.js
  app/javascript/react/screens/App/Plan/index.js
  app/javascript/react/screens/App/Plan/plan.fixtures.js
  app/javascript/react/screens/App/Plan/plan.planRequests.fixtures.js
  app/javascript/react/screens/App/Plan/plan.vms.fixtures.js
Labels: p3, sprint7

#249 Plans completed details
  app/javascript/react/screens/App/Overview/Overview.scss
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Plan/Plan.js
  app/javascript/react/screens/App/Plan/Plan.scss
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailListConstants.js
  app/javascript/react/screens/App/Plan/plan.fixtures.js
  app/javascript/react/screens/App/Plan/plan.planRequests.fixtures.js
Labels: enhancement, p1, sprint7

#263 Display a toast notification when a plan execution completes
  app/javascript/components/index.js
  app/javascript/react/index.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/__test__/Overview.test.js
  app/javascript/react/screens/App/Overview/__test__/OverviewActions.test.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/index.js
  app/javascript/react/screens/App/Plan/index.js
  app/javascript/react/screens/App/common/NotificationList/NotificationConstants.js
  app/javascript/react/screens/App/common/NotificationList/NotificationList.js
  app/javascript/react/screens/App/common/NotificationList/NotificationListActions.js
  app/javascript/react/screens/App/common/NotificationList/NotificationListReducer.js
  app/javascript/react/screens/App/common/NotificationList/__test__/NotificationList.test.js
  app/javascript/react/screens/App/common/NotificationList/__test__/__snapshots__/NotificationList.test.js.snap
  app/javascript/react/screens/App/common/NotificationList/index.js
  app/javascript/redux/reducers/index.js
Labels: enhancement, p1
