Repository ManageIQ/manageiq-v2v, pull requests merged in 2018-05, with the labels that each got.

#300 Fixes notification removal
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCards.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/common/NotificationList/NotificationList.js
  app/javascript/react/screens/App/common/NotificationList/NotificationListActions.js
  app/javascript/react/screens/App/common/NotificationList/NotificationListReducer.js
  package.json
  yarn.lock
Labels: bug

#306 Adds id attribute (name) to encapsulating form input div
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/DualPaneMapper/DualPaneMapperList.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStep.js
  app/javascript/react/screens/App/common/forms/FormField.js
Labels: enhancement

#69 Remove unused test directory
  Rakefile
  test/controllers/plug_controller_test.rb
  test/integration/navigation_test.rb
  test/migration/Rakefile
  test/migration/app/assets/config/manifest.js
  test/migration/app/assets/images/.keep
  test/migration/app/assets/javascripts/application.js
  test/migration/app/assets/javascripts/cable.js
  test/migration/app/assets/javascripts/channels/.keep
  test/migration/app/assets/stylesheets/application.css
  test/migration/app/channels/application_cable/channel.rb
  test/migration/app/channels/application_cable/connection.rb
  test/migration/app/controllers/application_controller.rb
  test/migration/app/controllers/concerns/.keep
  test/migration/app/helpers/application_helper.rb
  test/migration/app/jobs/application_job.rb
  test/migration/app/mailers/application_mailer.rb
  test/migration/app/models/application_record.rb
  test/migration/app/models/concerns/.keep
  test/migration/bin/bundle
  test/migration/bin/rails
  test/migration/bin/rake
  test/migration/bin/setup
  test/migration/bin/update
  test/migration/config.ru
  test/migration/config/application.rb
  test/migration/config/boot.rb
  test/migration/config/cable.yml
  test/migration/config/database.yml
  test/migration/config/environment.rb
  test/migration/config/environments/development.rb
  test/migration/config/environments/production.rb
  test/migration/config/environments/test.rb
  test/migration/config/initializers/application_controller_renderer.rb
  test/migration/config/initializers/assets.rb
  test/migration/config/initializers/backtrace_silencers.rb
  test/migration/config/initializers/cookies_serializer.rb
  test/migration/config/initializers/filter_parameter_logging.rb
  test/migration/config/initializers/inflections.rb
  test/migration/config/initializers/mime_types.rb
  test/migration/config/initializers/new_framework_defaults.rb
  test/migration/config/initializers/session_store.rb
  test/migration/config/initializers/wrap_parameters.rb
  test/migration/config/locales/en.yml
  test/migration/config/puma.rb
  test/migration/config/routes.rb
  test/migration/config/secrets.yml
  test/migration/config/spring.rb
  test/migration/lib/assets/.keep
  test/migration/log/.keep
  test/migration/public/404.html
  test/migration/public/422.html
  test/migration/public/500.html
  test/migration/public/apple-touch-icon-precomposed.png
  test/migration/public/apple-touch-icon.png
  test/migration/public/favicon.ico
  test/miq_v2v_ui_test.rb
  test/test_helper.rb
Labels: ui-cleanup

#60 Remove extra directories
  app/jobs/miq_v2v_ui/application_job.rb
  app/mailers/miq_v2v_ui/application_mailer.rb
  app/models/miq_v2v_ui/application_record.rb
Labels: ui-cleanup

#313 Move planwizardvmstep table header into component for equal padding
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/PlanWizardVMStepTable.js
Labels: bug, ui-cleanup

#303 Use window api methods for correct session timeout
  .jest-setup.js
  app/javascript/common/API.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/OverviewActions.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/MappingWizardClusterStepActions.test.js.snap
  app/javascript/react/screens/App/Plan/__test__/__snapshots__/PlanActions.test.js.snap
  package.json
Labels: blocker, bug

#336 Remove unused npm deps
  package.json
Labels: gaprindashvili/yes

#332 update v2v readme
  README.md
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsNotStartedList.test.js
Labels: gaprindashvili/yes

#333 rails controllers - use default set of action filters, including check_privileges
  app/controllers/migration_controller.rb
  app/controllers/migration_log_controller.rb
Labels: gaprindashvili/yes

#330 Remove unused MiqV2vUI::ApplicationController
  app/assets/config/miq_v2v_ui_manifest.js
  app/controllers/miq_v2v_ui/application_controller.rb
Labels: gaprindashvili/yes

#328 Remove v2v-mappings-content image - no longer referenced
  app/assets/images/miq_v2v_ui/.keep
  app/assets/images/miq_v2v_ui/v2v-mappings-content@2x.png
Labels: gaprindashvili/yes

#329 Remove another test app
  test/migration/app/views/layouts/application.html.haml
  test/migration/app/views/layouts/mailer.html.haml
  test/migration/app/views/layouts/mailer.text.haml
Labels: gaprindashvili/yes

#335 BootstrapSelect - use global jQuery
  .eslintrc.js
  app/javascript/react/screens/App/common/forms/BootstrapSelect.js
  package.json
  yarn.lock
Labels: gaprindashvili/yes

#331 Use standard application layout
  app/controllers/migration_controller.rb
  app/views/layouts/_full_center_v2v.html.haml
  app/views/layouts/migration.html.haml
  app/views/migration/index.html.haml
Labels: gaprindashvili/yes

#340 Use http, not API for querying rails controller endpoints
  app/javascript/common/API.js
  app/javascript/common/http.js
  app/javascript/react/screens/App/Plan/PlanActions.js
Labels: gaprindashvili/yes

#334 Move componentRegistry, mount, mount_react_component to v2v
  .eslintrc.js
  app/controllers/migration_controller.rb
  app/javascript/components/componentRegistry.js
  app/javascript/components/componentRegistry.test.js
  app/javascript/components/mounter.js
  app/javascript/packs/migration.js
Labels: gaprindashvili/yes

#354 wizard-pf-main - update margin for patternfly 3.25 compatibility
  app/javascript/react/screens/App/Overview/Overview.scss
Labels: gaprindashvili/yes

#364 Depend on transform-es2015-modules-commonjs, mentioned in .babelrc
  package.json
  yarn.lock
Labels: gaprindashvili/yes
