Repository ManageIQ/manageiq-v2v, pull requests merged in 2018-09, with the labels that each got.

#562 [#546][2 of (3)?] OSP Support: Add editable Instance Properties table to Plan Wizard
  app/assets/stylesheets/manageiq-v2v/base.scss
  app/javascript/components/index.js
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.scss
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.scss
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepActions.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepConstants.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepReducer.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/components/InlineEdit/CancelButton.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/components/InlineEdit/ConfirmButton.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/components/PlanWizardInstancePropertiesStepTable.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/components/TableInlineEditRow/TableConfirmButtonsRow.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/components/TableInlineEditRow/TableInlineEditRow.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/components/TableInlineEditRow/closestPolyfill.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/helpers.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/index.js
  app/javascript/redux/reducers/index.js
  package.json
  yarn.lock
Labels: Sprint 13

#630 Use `isFetchingTransformationMappings` for loading the mapping info
  app/javascript/react/screens/App/Overview/OverviewReducer.js
Labels: bug, gaprindashvili/no

#627 Integrate best fit flavor API with OSP Instance Properties
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardActions.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardConstants.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardSelectors.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepActions.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepConstants.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepReducer.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/components/PlanWizardInstancePropertiesStepTable.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/index.js
  package.json
Labels: enhancement

#635 Update yarn.lock for lodash.findindex removal
  yarn.lock
Labels: dependencies

#637 [Fix #636] Fix Next button never being disabled on the VM step
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepActions.js
Labels: bug

#645 Prefill with default security group(from API) and largest disk size flavor for no bestfit flavor cases
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepReducer.js
Labels: v1.1

#618 Adjust UI based on the backend refactored logic for VM discovery/CSV process
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepReducer.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/helpers.js
Labels: Sprint 13, gaprindashvili/no, refactoring

#619 [#610] Migration tasks in progress: Move description/playbook out of tooltip
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: Sprint 13, enhancement, v1.1

#668 Make menu item keys more unique
  app/javascript/react/screens/App/common/forms/BootstrapSelect.js
Labels: Sprint 14, bug, hammer/yes

#658 POST body changes for OSP based Plans
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/components/PlanWizardInstancePropertiesStepTable.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/helpers.js
Labels: Sprint 14, enhancement, hammer/yes

#660 [#606] Edit Mapping
  app/javascript/components/index.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/InfrastructureMappingsList.js
  app/javascript/react/screens/App/Overview/components/Migrations/DeleteMigrationMenuItem.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizard.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizard.scss
  app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardActions.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardBody.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/__tests__/__snapshots__/MappingWizard.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/__tests__/index.test.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepReducer.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/index.test.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/helpers.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepTreeView.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepActions.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepReducer.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/helpers.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStepActions.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStepConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStepReducer.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/helpers.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepReducer.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/helpers.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStepActions.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStepConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStepReducer.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardResultsStep/helpers.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardResultsStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardTreeView/MappingWizardTreeView.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/helpers.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/helpers.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardActions.js
  app/javascript/redux/reducers/index.js
Labels: Sprint 14, enhancement, hammer/yes

#671 [#652] Plan Details: Initially sort by VM name
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: Sprint 14, hammer/yes

#669 [#644] Instance Properties Step: Add warning for flavors which may not be big enough
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.scss
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepReducer.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/components/PlanWizardInstancePropertiesStepTable.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/components/sortableHeaderCellFormatterWithChildren.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/helpers.js
Labels: Sprint 14, hammer/yes

#657 [#648] Add selected counts to target object lists in the infra mapping wizard
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/DualPaneMapper/DualPaneMapperCount.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
Labels: Sprint 14, hammer/yes, ui-cleanup

#670 [#653] Fixes misalignment issues in the Plan detail list when download log is in progress
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: bug, hammer/yes
