Repository ManageIQ/manageiq-v2v, pull requests merged in 2018-07, with the labels that each got.

#460 Check for valid `vms` before calculating the in active VMs length
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepReducer.js
Labels: blocker, bug, gaprindashvili/yes

#461 [GAPRINDASHVILI] Check for valid `vms` before calculating the in active VMs length
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepReducer.js
Labels: bug

#453 [#424] schema validators for Overview screen
  app/javascript/data/models/clusters.js
  app/javascript/data/models/datastores.js
  app/javascript/data/models/networks.js
  app/javascript/data/models/plans.js
  app/javascript/data/models/provider.js
  app/javascript/data/models/requests.js
  app/javascript/data/models/transformationMappings.js
  app/javascript/data/schemaHelpers.js
  app/javascript/packs/migration.js
  app/javascript/packs/polyfills.js
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/OverviewValidators.js
  package.json
  yarn.lock
Labels: enhancement, gaprindashvili/no

#470 [#455] use lan id and uid_ems to uniquely identify network
  app/javascript/components/index.js
  app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/helpers.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepActions.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepSelectors.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/__tests__/MappingWizardNetworksStepSelectors.test.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/__tests__/__snapshots__/MappingWizardDatastoresStepReducer.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/__tests__/__snapshots__/MappingWizardNetworksStepSelectors.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/__tests__/NetworksStepForm.test.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/__tests__/__snapshots__/helpers.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/__tests__/helpers.test.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/helpers.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/mappingWizardNetworksStep.fixtures.js
  app/javascript/react/screens/App/common/networkKey.js
Labels: blocker, bug, gaprindashvili/yes

#472 [#471] pass empty pre and post playbooks to bypass playbook support for now
  app/javascript/data/models/plans.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/overview.transformationPlans.fixtures.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/planWizardResultsStep.fixtures.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/helpers.js
  app/javascript/react/screens/App/Plan/Plan.js
Labels: gaprindashvili/yes

#468 [#437] Resolve all Retry Migration issues
  app/javascript/components/index.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
  app/javascript/react/screens/App/Overview/components/Migrations/helpers/getMostRecentVMTasksFromRequests.js
  app/javascript/react/screens/App/Overview/overview.requestWithTasks.fixtures.js
  app/javascript/react/screens/App/Overview/overview.transformationPlans.fixtures.js
  app/javascript/react/screens/App/Plan/Plan.js
  app/javascript/react/screens/App/Plan/PlanActions.js
  app/javascript/react/screens/App/Plan/PlanConstants.js
  app/javascript/react/screens/App/Plan/PlanReducer.js
  app/javascript/react/screens/App/common/commonUtilitiesHelper.js
Labels: blocker, bug, gaprindashvili/yes

#474 [#451] duplicate plan name validation
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/__test__/Overview.test.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/overview.fixtures.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizard.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardActions.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardBody.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardConstants.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardReducer.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/PlanWizardGeneralStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/helpers.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/index.js
Labels: Sprint 10, bug, gaprindashvili/yes

#479 Fix the Archived Plan view
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
Labels: Sprint 10, blocker, bug, gaprindashvili/yes

#480 Display log location in the VM Migration Task Popover
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: bug, bugzilla needed, gaprindashvili/yes

#487 Undo the code that puts the master commit hash in the html
  app/controllers/migration_controller.rb
  app/views/migration/index.html.haml
Labels: bug, gaprindashvili/no

#476 Migration Status string constants for i18n
  app/javascript/react/screens/App/Plan/PlanConstants.js
  app/javascript/react/screens/App/Plan/PlanReducer.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailListConstants.js
Labels: bugzilla needed, gaprindashvili/yes, internationalization

#401 [#369] Inactive migration plans can be scheduled to run
  app/javascript/components/index.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModal.js
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModalBody.js
Labels: Sprint 10, enhancement, gaprindashvili/yes

#489 archived plans should show if they exist
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/Migrations.test.js
Labels: Sprint 10, bug, gaprindashvili/yes

#488 add schedules schema validation to overview
  app/javascript/data/models/plans.js
  app/javascript/data/models/schedules.js
Labels: Sprint 10

#490 Remove Settings.product.transformation - no longer conditional on a product feature
  config/routes.rb
  lib/manageiq/v2v/engine.rb
Labels: bug, gaprindashvili/yes

#427 [#375] - Enables sorting for not yet/completed migrations
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.scss
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsConstants.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsCompletedList.test.js
Labels: bugzilla needed, enhancement, gaprindashvili/yes

#493 Hoisting plan status to finishedtransformationsplans requires immutable
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
Labels: bug, bugzilla needed

#494 Show the archived plans in the Archived Plan view
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
Labels: bug, bugzilla needed, gaprindashvili/yes

#502 add button id's for migrate, schedule and unschedule
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
Labels: qe

#500 Adds infra mapping plan name to transformation plans
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsConstants.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/overview.transformationPlans.fixtures.js
  app/javascript/react/screens/App/common/getMostRecentRequest.js
Labels: Sprint 11, bugzilla needed, enhancement, gaprindashvili/yes, ux/review

#492 [GAPRINDASHVILI] Allow mapping Target Datasources that have less allocated space than Source Datastores #486
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/__tests__/DatastoresStepForm.test.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/helpers.js
Labels: bug

#497 Adds vm# sorting and clock icon to plan not started list
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
Labels: bug, bugzilla needed, gaprindashvili/yes

#413 [#368] Add Advanced Options Step to Plan Wizard
  app/javascript/components/index.js
  app/javascript/data/models/serviceTemplateAnsiblePlaybook.js
  app/javascript/data/models/serviceTemplateAnsiblePlaybooks.js
  app/javascript/react/screens/App/Overview/Overview.scss
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.scss
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardActions.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardBody.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardSelectors.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/PlanWizardAdvancedOptionsStep.fixtures.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/PlanWizardAdvancedOptionsStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/PlanWizardAdvancedOptionsStep.scss
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/PlanWizardAdvancedOptionsStepActions.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/PlanWizardAdvancedOptionsStepConstants.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/PlanWizardAdvancedOptionsStepReducer.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/PlanWizardAdvancedOptionsStepSelectors.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/PlanWizardAdvancedOptionsStepValidators.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/components/PlanWizardAdvancedOptionsStepTable/PlanWizardAdvancedOptionsStepTable.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/components/PlanWizardAdvancedOptionsStepTable/vmSelectionCellFormatter.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/components/PlanWizardAdvancedOptionsStepTable/vmSelectionHeaderCellFormatter.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/PlanWizardGeneralStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/PlanWizardScheduleStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/PlanWizardVMStepTable.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/common/CustomToolbarFind.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/common/rowFilter.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/common/searchFilter.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/helpers.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/index.js
  app/javascript/react/screens/App/common/forms/BootstrapSelect.js
  app/javascript/redux/reducers/index.js
Labels: bugzilla needed, enhancement, gaprindashvili/yes

#442 [#400] Plan details playbooks support
  app/javascript/components/index.js
  app/javascript/react/screens/App/Plan/Plan.js
  app/javascript/react/screens/App/Plan/PlanActions.js
  app/javascript/react/screens/App/Plan/PlanConstants.js
  app/javascript/react/screens/App/Plan/PlanReducer.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: enhancement, gaprindashvili/yes

#491 [#399] Pre/Post Playbook Overview UI + API
  app/javascript/components/index.js
  app/javascript/data/models/plans.js
  app/javascript/data/models/playbooks.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/OverviewValidators.js
  app/javascript/react/screens/App/Overview/__test__/Overview.test.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/components/AggregateCards/ActiveTransformationPlans/ActiveTransformationPlans.js
  app/javascript/react/screens/App/Overview/components/Migrations/InProgressCard.js
  app/javascript/react/screens/App/Overview/components/Migrations/InProgressWithDetailCard.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCards.js
  app/javascript/react/screens/App/Overview/components/Migrations/helpers/getPlaybookName.js
  app/javascript/react/screens/App/Overview/overview.fixtures.js
Labels: blocker, enhancement, gaprindashvili/yes

#516 [#240] Plan Wizard: Select valid VMs by default on CSV import, but not in discovery mode
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
Labels: bugzilla needed, gaprindashvili/yes

#517 [#370] Cancel a migration's in-progress tasks
  app/javascript/components/index.js
  app/javascript/react/screens/App/Plan/Plan.js
  app/javascript/react/screens/App/Plan/PlanActions.js
  app/javascript/react/screens/App/Plan/PlanConstants.js
  app/javascript/react/screens/App/Plan/PlanReducer.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: blocker, enhancement, gaprindashvili/yes

#521 [GAPRINDASHVILI] Resolve all Retry Migration issues
  app/javascript/components/index.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/helpers/getMostRecentVMTasksFromRequests.js
  app/javascript/react/screens/App/Overview/overview.requestWithTasks.fixtures.js
  app/javascript/react/screens/App/Overview/overview.transformationPlans.fixtures.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/planWizardResultsStep.fixtures.js
  app/javascript/react/screens/App/Plan/Plan.js
  app/javascript/react/screens/App/Plan/PlanActions.js
  app/javascript/react/screens/App/Plan/PlanConstants.js
  app/javascript/react/screens/App/Plan/PlanReducer.js
  app/javascript/react/screens/App/common/commonUtilitiesHelper.js
Labels: blocker

#514 [#515]Adds migration scheduling to complete mapping list
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/ScheduleMigrationButton.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsCompletedList.test.js
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModal.js
Labels: Sprint 11, enhancement

#510 [#505] OSP - Infra Mapping Wizard Step 1
  app/javascript/components/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardBody.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/__tests__/index.test.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/index.test.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/mappingWizardClustersStep.fixtures.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepActions.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepActions.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/index.js
  app/javascript/react/screens/App/common/forms/BootstrapSelect.js
Labels: Sprint 11, enhancement, gaprindashvili/no
