Repository ManageIQ/manageiq-v2v, pull requests merged in 2018-11, with the labels that each got.

#743 [HAMMER] Add translations for hammer
  locale/es/ManageIQ_V2V.po
  locale/fr/ManageIQ_V2V.po
  locale/ja/ManageIQ_V2V.po
  locale/pt_BR/ManageIQ_V2V.po
  locale/zh_CN/ManageIQ_V2V.po
Labels: internationalization

#760 [#759] Prevent 'All source clusters mapped' message when there are no source clusters
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
Labels: bug, hammer/yes, v1.1

#772 [#771] Add unique identifiers for filter type selects
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/components/PlanWizardAdvancedOptionsStepTable/PlanWizardAdvancedOptionsStepTable.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/PlanWizardVMStepTable.js
Labels: qe

#775 [#774] Update provider requirements
  app/javascript/react/screens/App/Mappings/Mappings.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/helpers.js
Labels: Sprint 16, bug, hammer/yes, v1.1

#765 [#764] Add warning if mapping changes when editing a plan
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/PlanWizardGeneralStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/helpers.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/index.js
Labels: Sprint 16, enhancement, hammer/yes, v1.1

#763 [#761] [Code Cleanup] Incorporate <ListViewToolbar /> with PlanRequestDetailList
  app/javascript/react/screens/App/Plan/Plan.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
  app/javascript/react/screens/App/common/ListViewToolbar/ListViewToolbar.js
Labels: Sprint 16, hammer/yes, technical debt, v1.1

#777 [#762] [Code Cleanup] Incorporate <ListViewToolbar /> with PlanVmsList
  app/javascript/react/screens/App/Plan/components/PlanVmsList.js
Labels: Sprint 16, hammer/yes, technical debt, v1.1

#781 [#780] Remove horizontal overflow
  app/javascript/react/screens/App/Overview/Overview.js
Labels: bug, hammer/yes, v1.1

#779 Remove outdated mount_react_component.
  app/controllers/migration_controller.rb
  app/javascript/components/mounter.js
  app/javascript/packs/migration.js
Labels: hammer/no, refactoring

#782 [#776] Add Migration Settings page with max concurrent migrations per host setting
  app/javascript/components/index.js
  app/javascript/react/config/config.js
  app/javascript/react/screens/App/App.scss
  app/javascript/react/screens/App/Settings/Settings.js
  app/javascript/react/screens/App/Settings/Settings.scss
  app/javascript/react/screens/App/Settings/SettingsActions.js
  app/javascript/react/screens/App/Settings/SettingsConstants.js
  app/javascript/react/screens/App/Settings/SettingsReducer.js
  app/javascript/react/screens/App/Settings/helpers.js
  app/javascript/react/screens/App/Settings/index.js
  app/javascript/react/screens/App/common/forms/NumberInput.js
  app/javascript/redux/reducers/index.js
  lib/manageiq/v2v/engine.rb
  package.json
  yarn.lock
Labels: Sprint 16, enhancement, hammer/yes, v1.1

#784 [GAPRINDASHVILI] Retrieve `transformation_mapping` via the service_templates API
  app/javascript/components/index.js
  app/javascript/react/screens/App/Overview/helpers.js
Labels: bug

#778 [#753] Public cloud networks
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepActions.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepConstants.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepReducer.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepSelectors.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/__tests__/__snapshots__/MappingWizardDatastoresStepReducer.test.js.snap
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/helpers.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/index.js
Labels: Sprint 16, enhancement, hammer/yes, v1.1

#791 [#773] conversion host name
  app/javascript/data/models/requests.js
  app/javascript/react/screens/App/Overview/overview.requestWithTasks.fixtures.js
  app/javascript/react/screens/App/Plan/Plan.js
  app/javascript/react/screens/App/Plan/PlanActions.js
  app/javascript/react/screens/App/Plan/PlanConstants.js
  app/javascript/react/screens/App/Plan/PlanReducer.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
  app/javascript/react/screens/App/Plan/helpers.js
  app/javascript/react/screens/App/Plan/plan.planRequests.fixtures.js
  app/javascript/react/screens/App/common/ListViewToolbar/sortFilter.js
Labels: bug, hammer/yes, v1.1

#788 Enable editing orphaned plans and handle undefined mapping when editing
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/PlanWizardGeneralStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/index.js
  app/javascript/react/screens/App/common/ConfirmModal.js
Labels: enhancement, hammer/yes, v1.1

#769 Fix vertical navigation menu for v2v
  app/controllers/migration_controller.rb
  app/javascript/react/config/Routes.js
  app/javascript/react/config/config.js
  app/javascript/react/index.js
  app/javascript/react/screens/App/Mappings/Mappings.js
  app/javascript/react/screens/App/Mappings/MappingsConstants.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepConstants.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepConstants.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStep.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/components/Migrations/InProgressWithDetailCard.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsNotStartedList.test.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.js
  app/javascript/react/screens/App/Plan/Plan.js
  app/javascript/react/screens/App/common/NotificationList/NotificationList.js
  app/javascript/redux/actions/routerActions.js
  config/routes.rb
  lib/manageiq/v2v/engine.rb
Labels: Sprint 16, hammer/yes, v1.1

#799 [#795] Fix missing networks and datastores
  app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/InfrastructureMappingsListConstants.js
  app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/helpers.js
Labels: bug, hammer/yes, v1.1

#796 Fix router warnings on component unmount
  app/javascript/react/screens/App/Mappings/Mappings.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Plan/Plan.js
Labels: hammer/yes

#787 [#785] Add defensive coding to helpers
  app/javascript/react/screens/App/Overview/components/Migrations/helpers/getMostRecentVMTasksFromRequests.js
  app/javascript/react/screens/App/common/commonUtilitiesHelper.js
Labels: bug, hammer/yes, v1.1

#745 [#715] Link directly from the Overview page to the Infra Mappings page without filter
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
Labels: hammer/yes, v1.1

#800 Fix/remove links
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStep.js
  app/javascript/react/screens/App/Overview/Overview.js
Labels: hammer/yes, v1.1

#798 [#786] Handle denied state of a plan request (no conversion hosts configured)
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/OverviewSelectors.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/components/AggregateCards/FinishedTransformationPlans/FinishedTransformationPlans.js
  app/javascript/react/screens/App/Overview/components/Migrations/InProgressCard.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCards.js
  app/javascript/react/screens/App/Plan/Plan.js
  app/javascript/react/screens/App/Plan/PlanConstants.js
  app/javascript/react/screens/App/Plan/PlanReducer.js
  app/javascript/react/screens/App/Plan/components/PlanEmptyState.js
Labels: enhancement, hammer/yes, v1.1

#806 [#749] Disable edit button for broken mappings
  app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/InfrastructureMappingsList.js
Labels: bug, hammer/yes, v1.1

#807 [#740] Waiting for available conversion hosts
  .jest-setup.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/OverviewSelectors.js
  app/javascript/react/screens/App/Overview/__test__/OverviewActions.test.js
  app/javascript/react/screens/App/Overview/__test__/OverviewReducer.test.js
  app/javascript/react/screens/App/Overview/__test__/OverviewSelectors.test.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/OverviewActions.test.js.snap
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/components/Migrations/CardEmptyState.js
  app/javascript/react/screens/App/Overview/components/Migrations/CardFooter.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCards.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/CardEmptyState.test.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/CardFooter.test.js
  app/javascript/react/screens/App/Overview/components/Migrations/helpers.js
  app/javascript/react/screens/App/Overview/index.js
  app/javascript/react/screens/App/Overview/overview.cancelRequest.fixtures.js
  app/javascript/react/screens/App/Overview/overview.fixtures.js
  app/javascript/react/screens/App/Overview/overview.transformationPlans.fixtures.js
Labels: enhancement, hammer/yes, v1.1
