Repository ManageIQ/manageiq-v2v, pull requests merged in 2018-08, with the labels that each got.

#529 [#528] Do not overwrite selected target provider
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStep.js
Labels: Sprint 11, bug

#525 [GAPRINDASHVILI] Cancel a migration's in-progress tasks
  app/javascript/components/index.js
  app/javascript/react/screens/App/Plan/Plan.js
  app/javascript/react/screens/App/Plan/PlanActions.js
  app/javascript/react/screens/App/Plan/PlanConstants.js
  app/javascript/react/screens/App/Plan/PlanReducer.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: blocker, enhancement

#527 [GAPRINDASHVILI] Pre/Post Playbook Overview UI + API
  app/javascript/components/index.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/__test__/Overview.test.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/components/AggregateCards/ActiveTransformationPlans/ActiveTransformationPlans.js
  app/javascript/react/screens/App/Overview/components/Migrations/InProgressCard.js
  app/javascript/react/screens/App/Overview/components/Migrations/InProgressWithDetailCard.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCards.js
  app/javascript/react/screens/App/Overview/components/Migrations/helpers/getPlaybookName.js
  app/javascript/react/screens/App/Overview/overview.fixtures.js
  app/javascript/react/screens/App/Plan/PlanConstants.js
Labels: blocker, enhancement

#439 [#387] View Migrations when there are no infra mappings
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/__test__/OverviewReducer.test.js
  app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/InfrastructureMappingsList.js
  app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/InfrastructureMappingsList.scss
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/ScheduleMigrationButton.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsCompletedList.test.js
  app/javascript/react/screens/App/Overview/overview.transformationPlans.fixtures.js
Labels: Sprint 11, enhancement, gaprindashvili/yes

#526 [#189] Warning for No Enabled Conversion Host in Target Cluster
  app/javascript/components/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/DualPaneMapper/DualPaneMapper.scss
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/DualPaneMapper/DualPaneMapperListItem.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepActions.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepReducer.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/MappingWizardClustersStepReducers.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
Labels: Sprint 11, blocker, enhancement, gaprindashvili/yes

#534 [GAPRINDASHVILI] Update gettext catalog for gaprindashvili update
  locale/MiqV2vUI.pot
Labels: internationalization

#538 Ensures filters aren't case sensitive removes duplicate files
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/CustomToolbarFind.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/rowFilter.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/searchFilter.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/common/rowFilter.js
Labels: blocker, bug, gaprindashvili/yes

#540 Fix PropType warning around warningMessage for target clusters
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
Labels: bug, gaprindashvili/no

#541 [#466] Fix the Plan Wizard Results Step API Error Handling
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStepActions.js
Labels: Sprint 12, blocker, bug, gaprindashvili/yes

#531 [#507] OSP - Infra Mapping Wizard Step 3
  app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepActions.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/helpers.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/helpers.js
Labels: Sprint 11, enhancement, gaprindashvili/no

#552 [#545] Log not available until playbook run complete
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: blocker, bug, gaprindashvili/yes

#530 [#508] OSP - Infra Mapping Wizard Step 4
  app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepActions.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStepConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/helpers.js
  app/javascript/react/screens/App/common/networkKey.js
Labels: Sprint 11, enhancement, gaprindashvili/no

#554 Adds plan transmutation to archived plans, creates inframappingname key
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/helpers.js
Labels: blocker, bug, gaprindashvili/yes

#543 [#265] Display successful/unsuccessful migration notifications in Plan detail page for in-progress->just completed tasks
  app/javascript/react/screens/App/Plan/Plan.js
  app/javascript/react/screens/App/Plan/PlanActions.js
  app/javascript/react/screens/App/Plan/PlanConstants.js
  app/javascript/react/screens/App/Plan/PlanReducer.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: blocker, bug, bugzilla needed, gaprindashvili/yes

#539 [GAPRINDASHVILI] Warning for No Enabled Conversion Host in Target Cluster
  app/javascript/components/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/DualPaneMapper/DualPaneMapper.scss
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/DualPaneMapper/DualPaneMapperListItem.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepActions.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepReducer.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/MappingWizardClustersStepReducers.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
Labels: blocker, bug

#557 [GAPRINDASHVILI]Fix travis failure
  app/javascript/react/screens/App/Overview/OverviewReducer.js
Labels: blocker, bug

#553 Update createTransformationMappings helper
  app/javascript/react/screens/App/Overview/screens/MappingWizard/helpers.js
Labels: Sprint 12, enhancement

#561 Do not fetch hosts if there are no targets
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
Labels: bug, bugzilla needed, gaprindashvili/yes

#566 select initial rows on vm csv import
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/PlanWizardVMStepTable.js
Labels: blocker, bug, gaprindashvili/yes

#547 [#546][1 of 2] OSP Support: Add (disabled) Instance Properties step in Plan Wizard
  app/javascript/components/index.js
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardBody.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardSelectors.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.scss
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepActions.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepReducer.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/index.js
Labels: Sprint 12, gaprindashvili/no

#568 [GAPRINDASHVILI] Update translations for gaprindashvili update release
  locale/es/MiqV2vUI.po
  locale/fr/MiqV2vUI.po
  locale/ja/MiqV2vUI.po
  locale/pt_BR/MiqV2vUI.po
  locale/zanata.xml
  locale/zh_CN/MiqV2vUI.po
Labels: blocker, internationalization, waiting-on-another-issue

#569 Update gettext catalogs for master
  locale/ManageIQ_V2V.pot
  locale/MiqV2vUI.pot
  locale/en/ManageIQ_V2V.po
  locale/en/MiqV2vUI.po
  locale/es/ManageIQ_V2V.po
  locale/es/MiqV2vUI.po
  locale/fr/ManageIQ_V2V.po
  locale/fr/MiqV2vUI.po
  locale/ja/ManageIQ_V2V.po
  locale/ja/MiqV2vUI.po
  locale/pt_BR/ManageIQ_V2V.po
  locale/pt_BR/MiqV2vUI.po
  locale/zanata.xml
  locale/zh_CN/ManageIQ_V2V.po
  locale/zh_CN/MiqV2vUI.po
Labels: gaprindashvili/no, internationalization

#565 Consistency of progress indication, round to nearest integer
  app/javascript/react/screens/App/Plan/PlanReducer.js
  app/javascript/react/screens/App/Plan/components/PlanVmsList.js
Labels: bug, gaprindashvili/yes

#575 Updates travis node targets to reflect miq supported versions
  .travis.yml
Labels: cleanup, developer, gaprindashvili/no

#533 Use ui classic redux and router
  .eslintrc.js
  app/assets/stylesheets/manageiq-v2v/base.scss
  app/javascript/components/index.js
  app/javascript/packs/migration.js
  app/javascript/react/config/config.js
  app/javascript/react/index.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/components/DeleteInfrastructureMappingConfirmationModal/DeleteInfrastructureMappingConfirmationModal.js
  app/javascript/react/screens/App/Overview/components/Migrations/InProgressWithDetailCard.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsNotStartedList.test.js
  app/javascript/react/screens/App/Overview/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/PlanWizardAdvancedOptionsStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
  app/javascript/react/screens/App/Plan/Plan.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
  app/javascript/react/screens/App/common/NotificationList/NotificationList.js
  app/javascript/redux/actions/routerActions.js
  app/javascript/redux/reducers/index.js
  app/javascript/redux/reducers/registerReducer.js
  app/views/migration/index.html.haml
  package.json
  yarn.lock
Labels: bug, gaprindashvili/no

#580 [3579] Long string overflow resolved by removing popover max-width property
  app/javascript/react/screens/App/Plan/Plan.scss
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: Sprint 12, bug, gaprindashvili/yes

#582 Standardize Repo
  .travis.yml
  LICENSE.txt
  README.md
Labels: developer, documentation

#583 Fixed typo: infrastrucutre to infrastructure
  README.md
Labels: developer, documentation

#588 [#585] Add hosts attribute to API endpoint
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
Labels: bug, gaprindashvili/no

#586 [#585] Fix fetching hosts
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
Labels: blocker, bug, gaprindashvili/yes

#590 Ensures utc is used when editing a migration schedule
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModal.js
Labels: Sprint 12, blocker, bug, gaprindashvili/yes

#593 [#592] Change text to `Start Time` in the popover
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: bug, gaprindashvili/no

#595 Reset state when leaving Plan details page
  app/javascript/react/screens/App/Plan/PlanReducer.js
Labels: bug, gaprindashvili/yes

#597 [#591] Show Migrations section if archived plans exist
  app/javascript/react/screens/App/Overview/Overview.js
Labels: bug

#584 Abstracts reducer logic into helpers
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/helpers.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepReducer.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/helpers.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepReducer.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/helpers.js
  app/javascript/react/screens/App/Plan/PlanReducer.js
  app/javascript/react/screens/App/Plan/helpers.js
Labels: Sprint 12, gaprindashvili/no, technical debt

#601 Ensure only error notifications persist
  .eslintrc.js
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepActions.js
  app/javascript/react/screens/App/Plan/PlanActions.js
Labels: Sprint 12, bug

#599 [#577] Removes dead retry button from failed mapping creation
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStep.js
Labels: Sprint 12, bug

#602 Ensures schedule is cleared from modal upon successful submission
  app/javascript/react/screens/App/Overview/components/Migrations/ScheduleMigrationButton.js
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModal.js
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModalBody.js
Labels: blocker, bug, gaprindashvili/yes

#596 Updating rails -v it to match cui, keep v2v safe (from Hakiri criticism)
  manageiq-v2v.gemspec
Labels: bug, developer, technical debt

#605 Load mapping info for a plan only when available
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/__test__/OverviewReducer.test.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
Labels: bug, bugzilla needed

#603 Add plugin display name
  lib/manageiq/v2v/engine.rb
Labels: developer, enhancement

#614 [#611] When no clusters are discovered (and loading is done) display message
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
Labels: Sprint 13, enhancement, gaprindashvili/no

#616 [#615] Do not render Migrations if there are no plans
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/__test__/Overview.test.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/overview.fixtures.js
Labels: Sprint 13, bug, gaprindashvili/no

#622 Coerce array length checks to boolean values
  app/javascript/react/screens/App/Overview/Overview.js
Labels: bug, gaprindashvili/no
