Repository ManageIQ/manageiq-v2v, pull requests merged in 2018-03, with the labels that each got.

#48 Menu items are added via plugin
  README.md
  lib/miq_v2v_ui/engine.rb
Labels: enhancement

#115 Add validation for datastore mappings
  app/javascript/react/screens/App/Overview/Overview.scss
  app/javascript/react/screens/App/Overview/components/ModalWizard/ModalWizard.scss
  app/javascript/react/screens/App/Overview/components/ModalWizard/ModalWizardBody.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizard.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardActions.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardBody.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardReducer.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/__tests__/__snapshots__/MappingWizard.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/helpers.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/index.js
Labels: p1

#113 Add target cluster name to drop downs
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/SourceClusterSelect/SourceClusterSelect.js
Labels: p1

#123 Enable removal of leaf nodes
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardTreeView/MappingWizardTreeView.js
Labels: p2

#141 Test MappingWizardClustersStepReducers
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/MappingWizardClustersStepReducers.test.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/MappingWizardClustersStepReducers.test.js.snap
Labels: ui-cleanup

#142 Test datastores and networks reducers
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/__tests__/MappingWizardDatastoresStepReducer.test.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/__tests__/__snapshots__/MappingWizardDatastoresStepReducer.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/__tests__/MappingWizardDatastoresStepReducer.test.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/__tests__/__snapshots__/MappingWizardDatastoresStepReducer.test.js.snap
Labels: ui-cleanup

#143 Refactor #addMapping in ClustersStepForm
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/__tests__/ClustersStepForm.test.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/__tests__/__snapshots__/helpers.test.js.snap
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/__tests__/helpers.test.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/clustersStepForm.fixtures.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/helpers.js
Labels: ui-cleanup
