Repository ManageIQ/manageiq-v2v, pull requests merged in 2018-06, with the labels that each got.

#379 Emptystate.title is a required field, cannot be undefied, ie-empty
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/CSVDropzoneField.js
Labels: bug

#380 Updates lockfile
  yarn.lock
Labels: bug

#391 Add missing gettext
  app/javascript/react/screens/App/Overview/components/AggregateCards/ActiveTransformationPlans/ActiveTransformationPlans.js
  app/javascript/react/screens/App/Overview/components/AggregateCards/FinishedTransformationPlans/FinishedTransformationPlans.js
  app/javascript/react/screens/App/Overview/components/AggregateCards/InfrastructureMappings/InfrastructureMappings.js
  app/javascript/react/screens/App/Overview/components/AggregateCards/NotStartedTransformationPlans/NotStartedTransformationPlans.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/helpers.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/CSVDropzoneField.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/PlanWizardVMStepTable.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/vmSelectionCellFormatter.js
  app/javascript/react/screens/App/Plan/Plan.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailListConstants.js
Labels: gaprindashvili/yes

#390 Adds internationalization support for miq languages
  app/javascript/common/i18n.js
Labels: bug

#392 [Gaprindashvili] adds locale support for v2v
  app/javascript/common/i18n.js
Labels: bug

#367 Archive Plans
  app/javascript/components/index.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/__test__/OverviewActions.test.js
  app/javascript/react/screens/App/Overview/__test__/OverviewReducer.test.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/Migrations.test.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsCompletedList.test.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
  app/javascript/react/screens/App/common/ConfirmModal.js
Labels: p1, sprint9

#398 Display 'Duplicate VM' Reason for duplicate VMs discovered after the CSV parsing
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepConstants.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepReducer.js
Labels: blocker, bug, sprint9

#395 adds compound expansion infra mappings UI
  .eslintrc.js
  app/javascript/common/helpers.js
  app/javascript/components/dates/MomentDate.js
  app/javascript/components/index.js
  app/javascript/react/screens/App/App.scss
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/Overview.scss
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/__test__/Overview.test.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/InfrastructureMappingsList.js
  app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/InfrastructureMappingsList.scss
  app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/__test__/InfrastructureMappingList.test.js
  app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/components/MappingSource.js
  app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/components/MappingTarget.js
  app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/helpers.js
  app/javascript/react/screens/App/Overview/overview.fixtures.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: enhancement, p1, sprint9

#407 check for the `transformation` flag to enable/disable Migration
  config/routes.rb
  lib/miq_v2v_ui/engine.rb
Labels: blocker, p1

#409 sort mappings in desc order - newest on top
  app/javascript/components/index.js
Labels: blocker, bug

#410 Look for color-variables at correct place
  app/javascript/react/screens/App/App.scss
Labels: bug, gaprindashvili/yes, pr-up-for-review

#412 remove filter label
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/PlanWizardVMStepTable.js
Labels: bug

#411 i18n support for infra mapping labels
  .eslintrc.js
  app/javascript/common/helpers.js
  app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/InfrastructureMappingsList.js
Labels: enhancement

#416 move mapping description to list item
  app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/InfrastructureMappingsList.js
Labels: enhancement

#418 Make the elapsed time clocks start ticking!
  app/javascript/components/dates/IsoElapsedTime.js
  app/javascript/components/dates/TickingIsoElapsedTime.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
  app/javascript/react/screens/App/Plan/PlanReducer.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: enhancement

#344 Rename to manageiq-v2v
  Gemfile
  README.md
  Rakefile
  app/assets/config/manageiq-v2v_manifest.js
  app/assets/images/manageiq-v2v/.keep
  app/assets/stylesheets/manageiq-v2v/application.css
  app/assets/stylesheets/manageiq-v2v/base.scss
  app/controllers/migration_controller.rb
  app/javascript/components/index.js
  app/javascript/packs/migration.js
  app/views/layouts/_full_center_v2v.html.haml
  app/views/migration/index.html.haml
  bin/rails
  config/initializers/gettext.rb
  config/initializers/inflections.rb
  config/routes.rb
  lib/manageiq-v2v.rb
  lib/manageiq/v2v/engine.rb
  lib/manageiq/v2v/version.rb
  lib/miq_v2v_ui.rb
  lib/miq_v2v_ui/version.rb
  lib/tasks/manageiq-v2v_tasks.rake
  manageiq-v2v.gemspec
  package.json
Labels: p1

#421 Remove git-hooks to avoid build system issues
  .githooks/post-merge/check_package_json
  package.json
  yarn.lock
Labels: enhancement

#417 Use a new rbac feature id for the menu item.
  lib/manageiq/v2v/engine.rb
Labels: enhancement

#425 Use virtual columns when filtering archived plans
  app/javascript/components/index.js
  app/javascript/react/screens/App/Plan/PlanActions.js
  app/javascript/react/screens/App/Plan/PlanReducer.js
Labels: gaprindashvili/yes, refactoring

#426 move patternfly dependency to devDependencies
  .eslintrc.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/index.js
  app/javascript/react/screens/App/common/NotificationList/index.js
  package.json
  yarn.lock
Labels: enhancement, gaprindashvili/no

#436 Add v2v plugin branch and commit sha in the main html [#422]
  app/controllers/migration_controller.rb
  app/views/migration/index.html.haml
Labels: Sprint 10, enhancement, gaprindashvili/yes

#444 fix retry count
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
Labels: Sprint 10, bug, gaprindashvili/yes

#449 Adds ellipsis to migration not started description field
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
Labels: Sprint 10, bug, gaprindashvili/yes

#454 Only iterate through mostRecentRequests if it exists 😋
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
Labels: Sprint 10, bug, gaprindashvili/no

#457 Travis lints pretty code, this gives it pretty code
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
Labels: Sprint 10, bug, gaprindashvili/yes

#458 We gotta tell eslint to fail when prettier fails
  .eslintrc.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
  app/javascript/react/screens/App/Overview/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardResultsStep/index.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/index.js
  app/javascript/react/screens/App/Plan/index.js
  app/javascript/react/screens/App/common/NotificationList/index.js
Labels: Sprint 10, bug, gaprindashvili/no

#450 VMs in conflict could be valid hence make them selectable with a warning
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepConstants.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepReducer.js
Labels: Sprint 10, blocker, bug, gaprindashvili/yes
