Repository ManageIQ/manageiq-v2v, pull requests merged in 2018-10, with the labels that each got.

#674 [#607] Make OSP Instance Properties step compatible with Edit Plan and enable Edit Plan
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepActions.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepReducer.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepActions.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/helpers.js
Labels: Sprint 14, hammer/yes

#673 [#564] Map VMWare Storages to OSP CloudVolumeTypes
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/MappingWizardConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepActions.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/helpers.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStep.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStepConstants.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/helpers.js
  app/javascript/react/screens/App/common/forms/BootstrapSelect.js
Labels: Sprint 14, enhancement, hammer/yes

#680 Rename the `osp_` attributes to reflect that they are id's
  app/javascript/react/screens/App/Overview/screens/PlanWizard/helpers.js
Labels: hammer/yes

#684 [#678] Prevent API call for editing plan when no changes have been made
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/helpers.js
Labels: hammer/yes

#663 [#641] Add EditPlanNameModal for editing name and description of completed plans
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/components/EditPlanNameModal/EditPlanNameActions.js
  app/javascript/react/screens/App/Overview/components/EditPlanNameModal/EditPlanNameConstants.js
  app/javascript/react/screens/App/Overview/components/EditPlanNameModal/EditPlanNameModal.js
  app/javascript/react/screens/App/Overview/components/EditPlanNameModal/EditPlanNameReducer.js
  app/javascript/react/screens/App/Overview/components/EditPlanNameModal/index.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardGeneralStep/helpers.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/helpers.js
  app/javascript/redux/reducers/index.js
Labels: Sprint 14, hammer/yes

#685 Display Toast notifications in Plan detail page only on task changes
  app/javascript/react/screens/App/Plan/PlanReducer.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
  app/javascript/react/screens/App/Plan/helpers.js
Labels: bug, hammer/yes

#682 [#650] UX Changes for Step 2 of Plan Wizard
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.scss
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.scss
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/PlanWizardVMStepTable.js
Labels: hammer/yes

#664 [#639] Fix VM step reverting to pre-selected values on back button
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/index.js
Labels: hammer/yes

#692 [#689] Preserve playbook selections
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/PlanWizardAdvancedOptionsStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/helpers.js
Labels: Sprint 15, bugzilla needed, enhancement, hammer/yes, v1.1

#693 Fix OSP attribute names
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStepReducer.js
Labels: hammer/yes

#683 [HAMMER] Update i18n catalog for hammer
  locale/ManageIQ_V2V.pot
  locale/en/ManageIQ_V2V.po
  locale/es/ManageIQ_V2V.po
  locale/fr/ManageIQ_V2V.po
  locale/ja/ManageIQ_V2V.po
  locale/pt_BR/ManageIQ_V2V.po
  locale/zanata.xml
  locale/zh_CN/ManageIQ_V2V.po
Labels: internationalization

#698 Use new ManageIQ.redux.addReducer.
  app/javascript/react/index.js
  app/javascript/redux/reducers/index.js
Labels: enhancement, hammer/yes

#697 Add playbook status messages to the dictionary
  app/javascript/react/screens/App/Plan/PlanConstants.js
Labels: hammer/yes

#700 Use the new constant names - VM_TRANSFORMATIONS_COMPLETED and VM_TRANSFORMATIONS_FAILED
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailListConstants.js
  app/javascript/react/screens/App/Plan/helpers.js
Labels: bug, hammer/yes

#672 [#572] Update Infrastructure Mappings list to display OSP mappings
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/__test__/Overview.test.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/InfrastructureMappingsList.js
  app/javascript/react/screens/App/Overview/components/InfrastructureMappingsList/helpers.js
Labels: Sprint 14, hammer/yes

#696 Display the Transformation mapping info in the Plan list immediately when the list loads
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/__test__/OverviewReducer.test.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/helpers.js
Labels: hammer/yes

#703 [#617] Indicate that all source clusters/datastores/networks have been mapped
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
  app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
Labels: hammer/yes

#704 [#676] Add ids for progress bars in in-progress cards
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
Labels: hammer/yes, qe

#706 Keep the Download Log button disabled until v2v log is available
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
  app/javascript/react/screens/App/Plan/helpers.js
Labels: Sprint 15, hammer/yes, v1.1

#705 [#687][#688] Add VM power warnings for OpenStack to Plan wizard
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.scss
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardSelectors.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/PlanWizardScheduleStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/index.js
  app/javascript/react/screens/App/common/forms/FormField.js
Labels: bugzilla needed, hammer/yes, v1.1

#708 [699] Fix cancellation issues based on new backend changes
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
  app/javascript/react/screens/App/Plan/helpers.js
Labels: blocker, hammer/yes, v1.1

#719 [#712] Enable Schedule button with default time when schedule modal is mounted
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModalBody.js
Labels: hammer/yes, v1.1

#718 Prevent a stray 0 from appearing on plans with no schedule
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
Labels: bug, hammer/yes, v1.1

#727 V2V Overview menu item: fix menu item highlighting
  lib/manageiq/v2v/engine.rb
Labels: bug, hammer/yes

#722 [#376] Add Edit schedule feature, move Unschedule button to Delete schedule menu item
  app/javascript/react/screens/App/Overview/components/Migrations/DeleteMigrationMenuItem.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/ScheduleMigrationButtons.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsCompletedList.test.js
  app/javascript/react/screens/App/Overview/components/Migrations/helpers/getPlanScheduleInfo.js
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModal.js
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModalBody.js
Labels: enhancement, hammer/yes, v1.1

#732 [#731] Fix console error when editing a schedule less than 2 minutes in the future
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModalBody.js
Labels: hammer/yes, v1.1

#729 [#724] Add sorting, filtering and pagination to Migration Plan list views
  app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/InfrastructureMappingsList.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.scss
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsConstants.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCards.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsNotStartedList.test.js
  app/javascript/react/screens/App/common/ListViewToolbar/ListViewToolbar.js
Labels: Sprint 15, enhancement, hammer/yes, v1.1

#691 Fix VM validity during Plan Edit
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepActions.js
Labels: bug, hammer/yes

#661 Request completion notifications would now be backend-initiated hence remove the frontend request completion notifications
  app/javascript/react/screens/App/Overview/Overview.js
Labels: Sprint 15, hammer/yes

#736 [Code Cleanup] Deduplicate filter/sort/pagination elements into ListViewToolbar renderers
  app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/InfrastructureMappingsList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/common/ListViewToolbar/ListViewToolbar.js
Labels: hammer/yes, v1.1

#741 [#735] Remove outdated text regarding dropdown
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCards.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
Labels: bug, hammer/yes, v1.1

#730 [#723] Auto select migrations filter
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/OverviewReducer.js
  app/javascript/react/screens/App/Overview/__test__/OverviewActions.test.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/OverviewActions.test.js.snap
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/Migrations.test.js
Labels: Sprint 15, enhancement, hammer/yes, v1.1

#738 [#728] Pass a copy of listItems to be sorted
  app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/InfrastructureMappingsList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
  app/javascript/react/screens/App/Plan/components/PlanVmsList.js
  app/javascript/react/screens/App/common/ListViewToolbar/paginate.js
  app/javascript/react/screens/App/common/ListViewToolbar/sortFilter.js
Labels: bug, hammer/yes, v1.1
