Repository ManageIQ/manageiq-v2v, pull requests merged in 2019-03, with the labels that each got.

#883 Conversion Host Configuration Wizard - Step #4 - Results (without passing SSH keys)
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStep.js
  app/javascript/react/screens/App/Overview/Overview.scss
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStep.scss
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/__tests__/__snapshots__/PlanWizardResultsStep.test.js.snap
  app/javascript/react/screens/App/Settings/SettingsActions.js
  app/javascript/react/screens/App/Settings/SettingsConstants.js
  app/javascript/react/screens/App/Settings/SettingsReducer.js
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsReducer.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizard.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/ConversionHostWizardResultsStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/helpers.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/index.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/index.js
  app/javascript/react/screens/App/common/ModalWizard/ModalWizard.scss
  app/javascript/react/screens/App/common/WizardErrorState.js
  app/javascript/react/screens/App/common/WizardLoadingState.js
Labels: bz, enhancement, hammer/yes, v1.1, z-stream

#882 Conversion Host: list view phase 2
  app/javascript/react/screens/App/Settings/SettingsActions.js
  app/javascript/react/screens/App/Settings/SettingsConstants.js
  app/javascript/react/screens/App/Settings/SettingsReducer.js
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsReducer.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/ConversionHostsSettings.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostRemoveButton.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsList.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/DeleteConversionHostConfirmationModal.js
Labels: bz, enhancement, hammer/yes, v1.1, z-stream

#894 Conversion Host Configuration Wizard - use correct default cloud-user (with a dash) instead of cloud_user
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
Labels: bug, bz, hammer/yes, v1.1, z-stream

#887 V2v specify migration log type
  app/controllers/migration_log_controller.rb
Labels: bz, enhancement, hammer/yes, v1.1, z-stream

#888 [#885] Add Virt-v2v-wrapper log download menu item
  app/javascript/react/screens/App/Plan/PlanActions.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: bz, enhancement, hammer/yes, v1.1, z-stream

#889 Conversion Host Configuration - List view #3 - Polling for tasks and rendering enable/disable status
  app/javascript/react/screens/App/Settings/Settings.js
  app/javascript/react/screens/App/Settings/Settings.scss
  app/javascript/react/screens/App/Settings/SettingsActions.js
  app/javascript/react/screens/App/Settings/SettingsConstants.js
  app/javascript/react/screens/App/Settings/SettingsReducer.js
  app/javascript/react/screens/App/Settings/__tests__/SettingsReducer.test.js
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/Settings.test.js.snap
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsReducer.test.js.snap
  app/javascript/react/screens/App/Settings/helpers.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/ConversionHostsSettings.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/ConversionHostsSettingsConstants.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/__tests__/ConversionHostsSettings.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostRemoveButton.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/ConversionHostWizardHostsStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/index.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsList.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsListItem.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/DeleteConversionHostConfirmationModal.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/index.js
Labels: bz, enhancement, hammer/yes, v1.1, z-stream

#897 Add new options for migration throttling
  app/javascript/react/screens/App/Settings/Settings.scss
  app/javascript/react/screens/App/Settings/helpers.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/GeneralSettings.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/index.js
  app/javascript/react/screens/App/common/forms/TextInputWithCheckbox.js
Labels: enhancement, hammer/yes, unmergeable, v1.1, z-stream

#905 Fix tests we missed in PR #897
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsActions.test.js.snap
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsReducer.test.js.snap
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/__snapshots__/GeneralSettings.test.js.snap
  app/javascript/react/screens/App/Settings/settings.fixures.js
Labels: bug, bugzilla needed, hammer/yes, v1.1, z-stream

#893 Get rid of dangerouslySetInnerHTML
  .eslintrc.js
  app/javascript/react/screens/App/Mappings/components/DeleteInfrastructureMappingConfirmationModal/DeleteInfrastructureMappingConfirmationModal.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/WarningModal/WarningModal.scss
Labels: bug, bugzilla needed, hammer/yes, v1.1, z-stream

#906 Add info popover to broken infra mapping error icons
  app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/InfrastructureMappingsList.js
Labels: bz, enhancement, hammer/yes, v1.1, z-stream

#907 Conversion Host Settings page: Ensure task.meta will always be defined
  app/javascript/react/screens/App/Settings/helpers.js
Labels: bug, bz, hammer/yes, v1.1, z-stream

#908 Conversion Host Configuration Wizard - Properly pass SSH keys and VDDK path to API
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/helpers.js
Labels: bz, enhancement, hammer/yes, v1.1, z-stream

#909 Fix conversion host removal modal
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/DeleteConversionHostConfirmationModal.js
Labels: bug, enhancement, hammer/yes

#910 Update Download Log menu item names and mapping list error message
  app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/InfrastructureMappingsList.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: bz, cleanup, hammer/yes

#912 Change 'pre-migration' and 'post-migration' to 'premigration' and 'postmigration' across the UI
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/PlanWizardAdvancedOptionsStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/components/PlanWizardAdvancedOptionsStepTable/PlanWizardAdvancedOptionsStepTable.js
  app/javascript/react/screens/App/Plan/PlanConstants.js
Labels: bz, cleanup, hammer/yes, v1.2, z-stream

#913 Conversion Host Configuration Wizard - rename API field from ssh_key to conversion_host_ssh_private_key
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/helpers.js
Labels: bz, enhancement, hammer/yes, v1.2, z-stream

#918 [#734] Add 'Status Detail' enhanced error message to info popover on a migration task
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: bz, enhancement, hammer/yes, v1.2, z-stream

#917 [#914] Plan Wizard VMs Step - VMWare Folder View
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/__tests__/PlanWizardVMStepReducer.test.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/__tests__/helpers.test.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/components/PlanWizardVMStepTable.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/helpers.js
Labels: bz, enhancement, hammer/yes, v1.2, z-stream

#916 [#901] Conversion Host Enablement - List View - Add Retry button with modal for re-entering SSH keys
  app/javascript/common/constants.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepConstants.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepSelectors.js
  app/javascript/react/screens/App/Settings/SettingsActions.js
  app/javascript/react/screens/App/Settings/SettingsConstants.js
  app/javascript/react/screens/App/Settings/SettingsReducer.js
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsReducer.test.js.snap
  app/javascript/react/screens/App/Settings/helpers.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/ConversionHostsSettings.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostRetryButton.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsList.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsListItem.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/RetryConversionHostConfirmationModal.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/index.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/index.js
  app/javascript/react/screens/App/common/forms/SshKeyField.js
Labels: bz, enhancement, hammer/yes, v1.2, z-stream

#920 [BZ#1680521] Filter cloud_tenants to Openstack providers explicitly (prevents errors with RHV-4.3 providers)
  app/javascript/react/screens/App/Mappings/MappingsConstants.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/redux/common/targetResources/targetResourcesConstants.js
Labels: bug, bz, hammer/yes, v1.2, z-stream

#919 [Changelog] Initial changelog and Hammer-4 entry
  CHANGELOG.md
Labels: documentation, hammer/yes
