Repository ManageIQ/manageiq-v2v, pull requests merged in 2019-09, with the labels that each got.

#1024 [Changelog] Update for Sprint 119
  CHANGELOG.md
Labels: documentation

#1026 Remove unnecessary locale files
  locale/es/ManageIQ_V2V.po
  locale/fr/ManageIQ_V2V.po
  locale/ja/ManageIQ_V2V.po
  locale/pt_BR/ManageIQ_V2V.po
  locale/zanata.xml
  locale/zh_CN/ManageIQ_V2V.po
Labels: internationalization, ivanchuk/no

#1027 Completely remove gettext catalogs
  config/initializers/gettext.rb
  locale/ManageIQ_V2V.pot
  locale/en/ManageIQ_V2V.po
Labels: technical debt

#1028 [Changelog] Rollup of Ivanchuk releases
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#1035 Fix malformed __() gettext calls in mapping wizard
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
Labels: bug, bz, changelog/no, ivanchuk/yes

#1033 Fix error when selecting multiple source clusters in an infrastructure mapping
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
Labels: UI, bug, bz, changelog/yes, ivanchuk/yes

#1036 Remove dead V2V_EDIT_PLAN_TITLE_SHOW_ALERT V2V_EDIT_PLAN_TITLE_HIDE_ALERT
  app/javascript/react/screens/App/Overview/components/EditPlanNameModal/EditPlanNameReducer.js
Labels: cleanup

#1031 Convert list views to table structure to fix alignment issues
  app/javascript/react/screens/App/App.scss
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/__tests__/__snapshots__/MappingWizard.test.js.snap
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.scss
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/ScheduledTimeInfoItem.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsCompletedList.test.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsNotStartedList.test.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/__tests__/__snapshots__/PlanWizardVMStep.test.js.snap
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/Settings.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/ConversionHostWizardAuthenticationStep.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/__tests__/__snapshots__/ConversionHostWizard.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/__snapshots__/ConversionHostsList.test.js.snap
  app/javascript/react/screens/App/common/ListViewTable/ListViewTable.js
  app/javascript/react/screens/App/common/ListViewTable/ListViewTable.scss
  app/javascript/react/screens/App/common/ListViewTable/ListViewTableRow.js
  package.json
  yarn.lock
Labels: UI, bug, bz, technical debt
