Repository ManageIQ/manageiq-v2v, pull requests merged in 2019-11, with the labels that each got.

#1066 Update rubies tested on Travis CI to match core manageiq
  .travis.yml
Labels: blocker, technical debt

#1057 Add expandable row support to ListViewTable and convert PlanRequestDetailList into a ListViewTable
  app/javascript/react/screens/App/Overview/components/Migrations/MappingNameInfoItem.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationInProgressListItem.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.scss
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/NumVmsInfoItem.js
  app/javascript/react/screens/App/Overview/components/Migrations/ScheduledTimeInfoItem.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/__snapshots__/MigrationInProgressListItem.test.js.snap
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
  app/javascript/react/screens/App/common/ListViewTable/ListViewTable.js
  app/javascript/react/screens/App/common/ListViewTable/ListViewTable.scss
  app/javascript/react/screens/App/common/ListViewTable/ListViewTableInfoItem.js
  app/javascript/react/screens/App/common/ListViewTable/ListViewTableRow.js
Labels: UI, changelog/no, enhancement, ivanchuk/yes, warm migration

#1059 [#1040][#1743703] Don't display invalid conversion hosts
  app/javascript/react/screens/App/Settings/__tests__/helpers.test.js
  app/javascript/react/screens/App/Settings/helpers.js
  app/javascript/react/screens/App/Settings/settings.fixtures.js
Labels: UI, bug, bz, changelog/yes, ivanchuk/yes

#1060 [BZ#1755842] Expose transformation method in the conversion hosts list
  app/javascript/react/screens/App/Settings/__tests__/helpers.test.js
  app/javascript/react/screens/App/Settings/helpers.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsListItem.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/ConversionHostsListItem.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/__snapshots__/ConversionHostsListItem.test.js.snap
Labels: UI, bz, changelog/yes, enhancement, ivanchuk/yes

#1067 ScheduledTimeInfoItem: fix PropType for migrationScheduled
  app/javascript/react/screens/App/Overview/components/Migrations/ScheduledTimeInfoItem.js
Labels: bug

#1071 Fix usage of PropTypes.oneOfType
  app/javascript/react/screens/App/Overview/components/Migrations/ScheduledTimeInfoItem.js
Labels: bug

#1073 Rename max_concurrent_tasks_per_host setting
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsActions.test.js.snap
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsReducer.test.js.snap
  app/javascript/react/screens/App/Settings/helpers.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/GeneralSettings.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/__snapshots__/GeneralSettings.test.js.snap
  app/javascript/react/screens/App/Settings/settings.fixtures.js
Labels: enhancement, ivanchuk/yes
