Repository ManageIQ/manageiq-v2v, pull requests merged in 2019-07, with the labels that each got.

#999 [Changelog] Update for Hammer-8
  CHANGELOG.md
Labels: documentation, hammer/yes

#998 Breadcrumb switcher: add support for product features
  app/javascript/react/screens/App/Mappings/Mappings.js
  app/javascript/react/screens/App/Mappings/index.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/__test__/Overview.test.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/__test__/index.test.js
  app/javascript/react/screens/App/Overview/index.js
  app/javascript/react/screens/App/Settings/Settings.js
  app/javascript/react/screens/App/Settings/__tests__/Settings.test.js
  app/javascript/react/screens/App/Settings/index.js
  app/javascript/react/screens/App/common/MigrationBreadcrumbBar.js
  app/javascript/redux/common/productFeatures/productFeaturesActions.js
  app/javascript/redux/common/productFeatures/productFeaturesConstants.js
  app/javascript/redux/common/productFeatures/productFeaturesReducer.js
  app/javascript/redux/reducers/index.js
Labels: UI, bug, changelog/no, v1.3

#1003 Use 'Migration Plans' in product features
  db/fixtures/miq_product_features.yml
Labels: bug

#1007 Add assert_privileges() to download_migration_log()
  app/controllers/migration_log_controller.rb
Labels: bug, bz, gaprindashvili/yes, hammer/yes, ivanchuk/yes

#1008 Conversion Host Wizard: Set VDDK as default transformation method
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/ConversionHostWizardAuthenticationStep.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/index.test.js
Labels: changelog/yes, enhancement, ivanchuk/yes, v1.3

#1009 Hide Back and Cancel buttons on the last step of Migration wizards
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/MappingWizard.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/__tests__/__snapshots__/MappingWizard.test.js.snap
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizard.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/__tests__/__snapshots__/ConversionHostWizard.test.js.snap
Labels: bz, changelog/no, enhancement, ivanchuk/yes, v1.3
