Repository ManageIQ/manageiq-v2v, pull requests merged in 2019-10, with the labels that each got.

#1041 [#1038] [BZ#1755897] Remove warnings related to RSA auth and clean up unused code
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepActions.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepConstants.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepReducer.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/MappingWizardClusterStepActions.test.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/MappingWizardClustersStep.test.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/MappingWizardClustersStepReducers.test.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/MappingWizardClusterStepActions.test.js.snap
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/MappingWizardClustersStepReducers.test.js.snap
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/helpers.test.js.snap
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/helpers.test.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/__tests__/ClustersStepForm.test.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/__tests__/helpers.test.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/helpers.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/helpers.js
  app/javascript/react/screens/App/Overview/OverviewConstants.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsInProgressCard.test.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/__snapshots__/MigrationsInProgressCard.test.js.snap
  app/javascript/redux/common/providers/__tests__/providersHelpers.test.js
  app/javascript/redux/common/providers/__tests__/providersReducer.test.js
  app/javascript/redux/common/providers/providersHelpers.js
  app/javascript/redux/common/providers/providersReducer.js
Labels: UI, bz, ivanchuk/yes, technical debt

#1030 Update react version to 16.9.x
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/ConversionHostWizardAuthenticationStep.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/ConversionHostWizardAuthenticationStep.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/ConversionHostWizardHostsStep.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/__snapshots__/ConversionHostWizardHostsStep.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardLocationStep/ConversionHostWizardLocationStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardLocationStep/__tests__/ConversionHostWizardLocationStep.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardLocationStep/__tests__/__snapshots__/ConversionHostWizardLocationStep.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardLocationStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/RetryConversionHostConfirmationModal.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/__tests__/RetryConversionHostConfirmationModal.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/__tests__/__snapshots__/RetryConversionHostConfirmationModal.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/common/forms/TextFileField.js
  package.json
  yarn.lock
Labels: UI, changelog/no, technical debt, unmergeable

#1049 [#1046] Fix logic for determining if a migration task is completed successfully
  app/javascript/react/screens/App/Plan/helpers.js
Labels: UI, bug, bz, ivanchuk/yes

#1050 Convert data size units from GB to GiB
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/helpers.js
  app/javascript/react/screens/App/Plan/helpers.js
Labels: bug, bz, ivanchuk/yes

#1042 Warm migrations: wizard changes
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardActions.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardConstants.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardReducer.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/__tests__/__snapshots__/helpers.test.js.snap
  app/javascript/react/screens/App/Overview/screens/PlanWizard/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/screens/PlanWizard/__tests__/helpers.test.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStepActions.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/__tests__/PlanWizardResultsStep.test.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/__tests__/__snapshots__/PlanWizardResultsStep.test.js.snap
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/PlanWizardScheduleStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/__tests__/PlanWizardScheduleStep.test.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/__tests__/__snapshots__/PlanWizardScheduleStep.test.js.snap
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/helpers.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/planWizard.fixtures.js
  app/javascript/react/screens/App/common/forms/FormField.js
Labels: bugzilla needed, enhancement, ivanchuk/yes, warm migration

#1055 [#1045][BZ#1759062] Rearrange migration status messages to expose more descriptive information
  app/javascript/react/screens/App/Plan/PlanConstants.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailListConstants.js
  app/javascript/react/screens/App/Plan/helpers.js
Labels: UI, bug, ivanchuk/yes, warm migration

#1051 [HAMMER] Convert data size units from GB to GiB
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/helpers.js
  app/javascript/react/screens/App/Plan/helpers.js
Labels: bug, bz, changelog/yes
