Repository ManageIQ/manageiq-v2v, pull requests merged in 2019-04, with the labels that each got.

#924 Conversion Host Wizard: set the auth_user to 'root' for RHV hosts
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/helpers.js
Labels: bz, enhancement, hammer/yes, v1.2, z-stream

#925 [BZ#1692087] Fix breadcrumb bars to be consistent with the rest of CloudForms
  app/javascript/react/screens/App/Mappings/Mappings.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Plan/Plan.js
  app/javascript/react/screens/App/Settings/Settings.js
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/Settings.test.js.snap
Labels: bug, bz, hammer/yes, v1.2, z-stream

#923 Migration Plans in Progress page: fix error with deleted target provider
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
  app/javascript/react/screens/App/Overview/helpers.js
Labels: bug, hammer/yes

#926 Fix call to transformation_log_queue
  app/controllers/migration_log_controller.rb
Labels: bug, hammer/yes, transformation

#928 Conversion Host Settings - Unit tests for helpers, prevent corner case of reappearing failures
  app/javascript/react/screens/App/Settings/__tests__/helpers.test.js
  app/javascript/react/screens/App/Settings/helpers.js
Labels: bug, bz, hammer/yes, v1.2, z-stream

#929 [HAMMER] Fix backport of PR#871 by adding missing fixtures for providers tests
  app/javascript/redux/common/providers/providers.fixtures.js
Labels: bz, hammer/yes, v1.2, z-stream

#931 [BZ#1695470] Text changes to wizard errors and throttling info popover
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardResultsStep/MappingWizardResultsStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/PlanWizardResultsStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/ConversionHostWizardResultsStep.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/GeneralSettings.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/GeneralSettings.test.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/__snapshots__/GeneralSettings.test.js.snap
Labels: bz

#932 [BZ#1699343] Fix regression in CSV validation with invalid rows
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/__tests__/helpers.test.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/helpers.js
Labels: bug, bz, hammer/yes, v1.2, z-stream

#936 [#890] Rename unsafe/deprecated React lifecycle methods
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/MappingWizardNetworksStep.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
  app/javascript/react/screens/App/Overview/Overview.js
Labels: cleanup, low-priority, technical debt

#941 Fix inline edit buttons positioning by rendering as a child of an existing table cell
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/PlanWizardInstancePropertiesStep.scss
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardInstancePropertiesStep/components/TableInlineEditRow/TableConfirmButtonsRow.js
Labels: bug, bz, hammer/yes, v1.2

#915 [#911] Add validation to migration throttling inputs and add CPU throttling field
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsActions.test.js.snap
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsReducer.test.js.snap
  app/javascript/react/screens/App/Settings/helpers.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/GeneralSettings.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/__snapshots__/GeneralSettings.test.js.snap
  app/javascript/react/screens/App/Settings/settings.fixures.js
  app/javascript/react/screens/App/common/forms/TextInputWithCheckbox.js
Labels: enhancement, hammer/yes, v1.2, z-stream

#922 Enable (un-hide) the Conversion Hosts tab of the Settings page
  app/javascript/react/screens/App/Settings/Settings.js
  app/javascript/react/screens/App/Settings/index.js
Labels: bz, enhancement, hammer/yes, v1.2, z-stream

#939 [Changelog] Update for Hammer-5 release
  CHANGELOG.md
Labels: documentation, hammer/yes

#943 Change layout of throttling settings form from horizontal to vertical
  app/javascript/react/screens/App/Settings/Settings.scss
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/GeneralSettings.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/__snapshots__/GeneralSettings.test.js.snap
  app/javascript/react/screens/App/common/forms/TextInputWithCheckbox.js
Labels: bugzilla needed, enhancement, hammer/yes, v1.2

#945 [HAMMER] Change layout of throttling settings form from horizontal to vertical
  app/javascript/react/screens/App/Settings/Settings.scss
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/GeneralSettings.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/GeneralSettings.test.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/__snapshots__/GeneralSettings.test.js.snap
  app/javascript/react/screens/App/common/forms/TextInputWithCheckbox.js
Labels: bz, enhancement, v1.2, z-stream

#946 [Changelog] Removing PRs from changelog
  CHANGELOG.md
Labels: documentation, hammer/yes
