Repository ManageIQ/manageiq-v2v, pull requests merged in 2019-06, with the labels that each got.

#979 [Changelog] Update for Hammer-7
  CHANGELOG.md
Labels: documentation, hammer/yes

#967 Add help block to advanced options of migration plan wizard
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardAdvancedOptionsStep/PlanWizardAdvancedOptionsStep.js
Labels: UI, enhancement

#980 [#875] Replace Configure Providers button with distinct links to infra and cloud providers
  app/javascript/react/screens/App/Mappings/Mappings.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/__test__/Overview.test.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/Overview.test.js.snap
  app/javascript/react/screens/App/common/NoProvidersEmptyState.js
  app/javascript/react/screens/App/common/ShowWizardEmptyState/ShowWizardEmptyState.js
Labels: UI, bug, changelog/yes, hammer/no, v1.3

#982 Add 'Missing Providers' title to empty state, update empty state on conversion host settings page
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/Overview.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/ConversionHostsSettings.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/__tests__/ConversionHostsSettings.test.js
  app/javascript/react/screens/App/common/NoProvidersEmptyState.js
Labels: UI, bug, changelog/no, hammer/no, v1.3

#995 Move the Migration menu section to the top level, placed before Configuration (after Compute)
  app/javascript/react/screens/App/Mappings/Mappings.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Plan/Plan.js
  app/javascript/react/screens/App/Settings/Settings.js
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/Settings.test.js.snap
  app/javascript/react/screens/App/common/BreadcrumbPageSwitcher.js
  app/javascript/react/screens/App/common/MigrationBreadcrumbBar.js
  lib/manageiq/v2v/engine.rb
Labels: UI, enhancement, v1.3

#997 Make the rails initializer name unique so it can be referenced in other plugins
  lib/manageiq/v2v/engine.rb
Labels: UI, changelog/no, enhancement
