Repository ManageIQ/manageiq-v2v, pull requests merged in 2019-08, with the labels that each got.

#1015 [#1014][BZ#1693994] Fix conversion host name not appearing on plan details after conversion host is deleted
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: UI, bug, bz, changelog/yes, ivanchuk/yes, v1.3

#1017 [Changelog] Update for Ivanchuk Beta1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#1018 [Changelog] Update for Hammer-10
  CHANGELOG.md
Labels: documentation, hammer/yes

#1021 Fix task destruction for log download controller
  app/controllers/migration_log_controller.rb
Labels: blocker, bug, ivanchuk/yes
