Repository ManageIQ/manageiq-v2v, pull requests merged in 2019-12, with the labels that each got.

#1074 [IVANCHUK] (Fix for earlier backport) Convert data size units from GB to GiB
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressCard.js
Labels: UI, bug, bz

#1076 [#1054] Update migration status message map to match latest backend strings
  app/javascript/react/screens/App/Plan/PlanConstants.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailListConstants.js
Labels: bz, ivanchuk/yes, v1.3

#1075 Add popup for warm migrations
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/PlanWizardScheduleStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/__tests__/PlanWizardScheduleStep.test.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/__tests__/__snapshots__/PlanWizardScheduleStep.test.js.snap
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/index.js
  app/javascript/react/screens/App/common/forms/FormField.js
Labels: enhancement

#1079 Remove and ignore yarn.lock
  .gitignore
  yarn.lock
Labels: UI, cleanup
