Repository ManageIQ/manageiq-v2v, pull requests merged in 2019-05, with the labels that each got.

#948 Add Download Log action to conversion host list items that creates a file from context_data
  app/javascript/react/screens/App/Settings/SettingsActions.js
  app/javascript/react/screens/App/Settings/helpers.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/ConversionHostsSettings.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsList.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsListItem.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/index.js
Labels: bz, changelog/yes, enhancement, hammer/yes, v1.2, z-stream

#947 Mapping Wizard: filter datastores to only those with storage_domain_type === 'data'
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepActions.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/__tests__/MappingWizardDatastoresStepActions.test.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/__tests__/__snapshots__/MappingWizardDatastoresStepActions.test.js.snap
Labels: bug, bz, changelog/yes, hammer/yes, v1.2, z-stream

#934 [#927] Add option to sort plans by Completed time, and fix alignment in plan list views
  app/javascript/react/screens/App/Overview/components/Migrations/EditScheduleMenuItems.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.scss
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsConstants.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/ScheduleMigrationButton.js
  app/javascript/react/screens/App/Overview/helpers.js
  app/javascript/react/screens/App/Overview/overview.transformationPlans.fixtures.js
  app/javascript/react/screens/App/common/Visibility.js
Labels: bz, changelog/yes, enhancement, hammer/yes, v1.2, z-stream

#938 Finish unit tests for SettingsActions and SettingsReducers
  .jest-setup.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/__tests__/PlanWizardResultsStep.test.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/__tests__/__snapshots__/PlanWizardResultsStep.test.js.snap
  app/javascript/react/screens/App/Settings/SettingsReducer.js
  app/javascript/react/screens/App/Settings/__tests__/SettingsActions.test.js
  app/javascript/react/screens/App/Settings/__tests__/SettingsReducer.test.js
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsActions.test.js.snap
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsReducer.test.js.snap
  app/javascript/react/screens/App/Settings/__tests__/helpers.test.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/GeneralSettings.test.js
  app/javascript/react/screens/App/Settings/settings.fixtures.js
  app/javascript/react/screens/App/Settings/settings.fixures.js
  package.json
  yarn.lock
Labels: changelog/no, hammer/no, test

#949 [BZ#1701330] Only apply storage_domain_type filter on RHV datastores, not OSP.
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStepActions.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/__tests__/MappingWizardDatastoresStepActions.test.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/__tests__/__snapshots__/MappingWizardDatastoresStepActions.test.js.snap
Labels: bug, bz, changelog/no, hammer/yes, v1.2, z-stream

#952 [#951] [BZ#1708359] Add OpenStack Trusted CA Certificates field to Conversion Host Wizard
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/index.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/helpers.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/RetryConversionHostConfirmationModal.js
  app/javascript/react/screens/App/common/forms/TextFileField.js
  app/javascript/react/screens/App/common/forms/TextFileInput/TextFileInput.js
  app/javascript/react/screens/App/common/forms/TextFileInput/TextFileInput.scss
Labels: bug, bz, changelog/yes, hammer/yes, v1.2, z-stream

#950 Change plugin common methods to class methods
  lib/manageiq/v2v/engine.rb
Labels: technical debt

#953 Conversion Host Wizard: Authentication Step - Add info popover to VDDK library path field
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
Labels: bz, changelog/no, enhancement, hammer/yes, v1.2, z-stream

#955 [#954] [BZ#1708365] Mapping Wizard: Clusters Step - hide RSA key warning if all conversion hosts have authentications
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/__tests__/helpers.test.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/helpers.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStep.js
Labels: bug, bz, changelog/no, hammer/yes, v1.2, z-stream

#961 [#958] [BZ#1712806] Conversion Host Wizard: Auth Step - Force validation to re-run when verifyOpenstackCerts is toggled
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
Labels: bug, bz, hammer/yes, v1.2, z-stream

#962 [#957] [BZ#1712873] Prevent migration task info popovers with long error messages from being pushed off the screen
  app/javascript/react/screens/App/Plan/Plan.scss
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
Labels: bug, bz, hammer/yes, v1.2, z-stream

#944 [#884] Add missing unit tests for ConversionHostsSettings files
  app/javascript/react/screens/App/Mappings/Mappings.js
  app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/InfrastructureMappingsList.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/__tests__/ConversionHostsSettings.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/__tests__/index.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostRemoveButton.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostRetryButton.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/ConversionHostWizardAuthenticationStep.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/ConversionHostWizardAuthenticationStep.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/index.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/index.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/ConversionHostWizardHostsStep.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/__snapshots__/ConversionHostWizardHostsStep.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/index.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/index.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardLocationStep/__tests__/ConversionHostWizardLocationStep.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardLocationStep/__tests__/__snapshots__/ConversionHostWizardLocationStep.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardLocationStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardLocationStep/__tests__/index.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardLocationStep/index.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/ConversionHostWizardResultsStep.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/__snapshots__/ConversionHostWizardResultsStep.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/__snapshots__/helpers.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/helpers.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/index.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/index.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/__tests__/ConversionHostWizard.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/__tests__/ConversionHostWizardBody.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/__tests__/ConversionHostWizardSelectors.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/__tests__/__snapshots__/ConversionHostWizard.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/__tests__/__snapshots__/ConversionHostWizardBody.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/__tests__/index.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsEmptyState.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/__tests__/RetryConversionHostConfirmationModal.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/__tests__/__snapshots__/RetryConversionHostConfirmationModal.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/__tests__/index.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/ConversionHostRemoveButton.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/ConversionHostRetryButton.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/ConversionHostsEmptyState.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/ConversionHostsList.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/ConversionHostsListItem.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/DeleteConversionHostConfirmationModal.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/__snapshots__/ConversionHostRemoveButton.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/__snapshots__/ConversionHostRetryButton.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/__snapshots__/ConversionHostsEmptyState.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/__snapshots__/ConversionHostsList.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/__snapshots__/ConversionHostsListItem.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/__snapshots__/DeleteConversionHostConfirmationModal.test.js.snap
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/index.test.js
  app/javascript/react/screens/App/common/ShowWizardEmptyState/ShowWizardEmptyState.scss
Labels: changelog/no, hammer/no, test

#963 [#865][BZ#1670703] Add BreadcrumbPageSwitcher for Plans, Mappings and Settings pages
  app/assets/stylesheets/manageiq-v2v/base.scss
  app/assets/stylesheets/manageiq-v2v/breadcrumbswitcher-popover.scss
  app/javascript/react/screens/App/Mappings/Mappings.js
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Settings/Settings.js
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/Settings.test.js.snap
  app/javascript/react/screens/App/common/BreadcrumbPageSwitcher.js
Labels: UI, bz, changelog/yes, enhancement, hammer/yes, qe, v1.2, z-stream

#966 Mapping wizard general step: show applicable provider types only
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardGeneralStep/MappingWizardGeneralStep.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardGeneralStep/index.js
Labels: UI, changelog/yes, enhancement, hammer/no, v1.3
