Repository ManageIQ/manageiq-v2v, pull requests merged in 2020-10, with the labels that each got.

#1145 Use manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-v2v.gemspec
Labels: developer, enhancement

#1146 Set the version of file-selector to be stricter than in react-dropzone
  package.json
Labels: dependencies

#1148 remove default distro from .travis.yml
  .travis.yml
Labels: developer, test
