Repository ManageIQ/manageiq-v2v, pull requests merged in 2020-11, with the labels that each got.

#1150 Update node and ruby versions for Travis
  .travis.yml
Labels: test

#1151 [KASPAROV] Update node and ruby versions for Travis
  .travis.yml
Labels: jansa/yes?, test

#1149 [KASPAROV] yarn: lock versions by adding yarn.lock
  .gitignore
  yarn.lock
Labels: dependencies
