Repository ManageIQ/manageiq-v2v, pull requests merged in 2020-01, with the labels that each got.

#1083 Roll back to previously locked versions of packages that are causing test failures
  package.json
Labels: UI, dependencies, technical debt

#1082 Check for VDDK conversion hosts before allowing warm migration
  app/javascript/common/constants.js
  app/javascript/react/screens/App/Mappings/components/InfrastructureMappingsList/helpers.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/MappingWizard.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/MappingWizardActions.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/MappingWizardConstants.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/__tests__/__snapshots__/MappingWizard.test.js.snap
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizard.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardActions.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardConstants.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardReducer.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardSelectors.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/PlanWizardGeneralStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardGeneralStep/helpers.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardResultsStep/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/PlanWizardScheduleStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/__tests__/PlanWizardScheduleStep.test.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/__tests__/__snapshots__/PlanWizardScheduleStep.test.js.snap
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/index.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStep.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/PlanWizardVMStepActions.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/__tests__/PlanWizardVMStep.test.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardVMStep/index.js
  app/javascript/react/screens/App/Settings/SettingsConstants.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/ConversionHostsSettings.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/__tests__/__snapshots__/ConversionHostWizardBody.test.js.snap
  app/javascript/react/screens/App/common/ModalWizard/ModalWizard.scss
  app/javascript/react/screens/App/common/ModalWizard/ModalWizardBody.js
Labels: UI, bugzilla needed, changelog/no, ivanchuk/yes, needs-tests, v1.3, warm migration

#1086 [#1072] [BZ#1775998] Fix logic for providers check on Conversion Hosts Settings page
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/ConversionHostsSettings.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/__tests__/ConversionHostsSettings.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/index.js
  app/javascript/redux/common/providers/__tests__/providersHelpers.test.js
  app/javascript/redux/common/providers/__tests__/providersReducer.test.js
  app/javascript/redux/common/providers/providersHelpers.js
  app/javascript/redux/common/providers/providersReducer.js
Labels: UI, bug, bz, ivanchuk/yes

#1088 FormField: Don't render extraneous info popover
  app/javascript/react/screens/App/common/forms/FormField.js
Labels: bug

#1085 [Part of BZ#1789479] UI changes for UCI: use VMs instead of Hosts for RHV conversion host configuration
  app/javascript/common/constants.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepSelectors.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/ConversionHostWizardHostsStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/ConversionHostWizardHostsStep.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/__snapshots__/ConversionHostWizardHostsStep.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/index.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/RetryConversionHostConfirmationModal.js
  app/javascript/react/screens/App/common/forms/TypeAheadSelectField.js
  app/javascript/redux/common/targetResources/targetResourcesConstants.js
Labels: UI, ivanchuk/yes, v1.3

#1090 [#992][BZ#1752568] Fix "none found" / "all mapped" messages in networks and datastores steps of mapping wizard
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
Labels: UI, bug, bz, v1.3

#1092 Fix logic for detecting SSH transport method on a conversion host configuration task
  app/javascript/react/screens/App/Settings/__tests__/helpers.test.js
  app/javascript/react/screens/App/Settings/helpers.js
Labels: bug, bz, ivanchuk/yes, v1.3

#1091 Limit warm migration to RHV targets only
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardSelectors.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/PlanWizardScheduleStep.js
Labels: UI, bugzilla needed, enhancement, ivanchuk/yes, v1.3, warm migration

#1070 Schedule migration modal changes for warm migration
  app/javascript/react/screens/App/Overview/Overview.js
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/__test__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Overview/components/Migrations/CutoverTimeInfoItem.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationInProgressListItem.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/ScheduleMigrationButton.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationsNotStartedList.test.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/__snapshots__/MigrationInProgressListItem.test.js.snap
  app/javascript/react/screens/App/Overview/components/Migrations/helpers/getPlanScheduleInfo.js
  app/javascript/react/screens/App/Overview/components/Migrations/helpers/isPlanWarmMigration.js
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModal.js
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModalBody.js
  app/javascript/react/screens/App/Overview/helpers.js
Labels: UI, bugzilla needed, enhancement, ivanchuk/yes, needs-tests, warm migration
