Repository ManageIQ/manageiq-v2v, pull requests merged in 2020-04, with the labels that each got.

#1122 Allow warm migration for OSP plans
  app/javascript/react/screens/App/Overview/screens/PlanWizard/PlanWizardSelectors.js
  app/javascript/react/screens/App/Overview/screens/PlanWizard/components/PlanWizardScheduleStep/PlanWizardScheduleStep.js
Labels: bz, enhancement, ivanchuk/yes, v1.3, warm migration

#1124 [#900][BZ#1708367] Allow removal of a failed conversion host configuration task
  app/javascript/react/screens/App/Settings/SettingsActions.js
  app/javascript/react/screens/App/Settings/__tests__/SettingsActions.test.js
  app/javascript/react/screens/App/Settings/helpers.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/ConversionHostsSettings.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostRemoveButton.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsList.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostsListItem.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/DeleteConversionHostConfirmationModal.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/ConversionHostRemoveButton.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/ConversionHostsList.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/DeleteConversionHostConfirmationModal.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/__snapshots__/ConversionHostsList.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/__tests__/__snapshots__/ConversionHostsListItem.test.js.snap
Labels: bz, enhancement, ivanchuk/yes, v1.3

#1123 [BZ#1817096] Support for two-phase cold migrations
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationInProgressListItem.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailListItem.js
  app/javascript/react/screens/App/Plan/helpers.js
  app/javascript/react/screens/App/common/ListViewTable/ListViewTableRow.js
  app/javascript/react/screens/App/common/twoPhaseConstants.js
  app/javascript/react/screens/App/common/twoPhaseHelpers.js
Labels: bz, enhancement, ivanchuk/yes, warm migration

#1125 [BZ#1810091] Conversion Host Wizard: hide powered-off VMs
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/ConversionHostWizardHostsStep.js
Labels: bz, enhancement, ivanchuk/yes

#1128 Menu - move Migration before Control
  lib/manageiq/v2v/engine.rb
Labels: enhancement, jansa/yes?
