Repository ManageIQ/manageiq-v2v, pull requests merged in 2020-03, with the labels that each got.

#1117 [JANSA] yarn: lock versions by adding yarn.lock
  .gitignore
  yarn.lock
Labels: dependencies

#1118 [IVANCHUK] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#1119 Remaining warm migration UI changes (Plans and Plan Details views)
  app/javascript/react/screens/App/Overview/OverviewActions.js
  app/javascript/react/screens/App/Overview/components/Migrations/CutoverTimeInfoItem.js
  app/javascript/react/screens/App/Overview/components/Migrations/InProgressRow.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationInProgressListItem.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.scss
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsCompletedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsNotStartedList.js
  app/javascript/react/screens/App/Overview/components/Migrations/ScheduledTimeInfoItem.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/CutoverTimeInfoItem.test.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/__snapshots__/MigrationInProgressListItem.test.js.snap
  app/javascript/react/screens/App/Overview/components/Migrations/helpers/getPlanScheduleInfo.js
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/ScheduleMigrationModal.js
  app/javascript/react/screens/App/Overview/overview.transformationPlans.fixtures.js
  app/javascript/react/screens/App/Plan/Plan.scss
  app/javascript/react/screens/App/Plan/PlanConstants.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js
  app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailListItem.js
  app/javascript/react/screens/App/Plan/helpers.js
  app/javascript/react/screens/App/common/ListViewTable/ListViewTableRow.js
  app/javascript/react/screens/App/common/warmMigrationConstants.js
  app/javascript/react/screens/App/common/warmMigrationHelpers.js
Labels: bz, enhancement, ivanchuk/yes, needs-tests, v1.3, warm migration
