Repository ManageIQ/manageiq-v2v, pull requests merged in 2020-02, with the labels that each got.

#1095 Add functionality for deleting warm migration cutover date
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationInProgressListItem.js
  app/javascript/react/screens/App/Overview/components/Migrations/Migrations.js
  app/javascript/react/screens/App/Overview/components/Migrations/MigrationsInProgressList.js
Labels: bugzilla needed, enhancement, ivanchuk/yes, warm migration

#1102 Update react-dropzone version to 10.2.1
  app/javascript/react/screens/App/common/forms/TextFileInput/TextFileInput.js
  package.json
Labels: bug

#1103 Fix render loop in Conversion Host wizard caused by validation workaround
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/ConversionHostWizardAuthenticationStep.test.js.snap
Labels: UI, bug

#1099 [Part 2/2 of BZ#1789479] UI changes for UCI: disable CPU throttling, accept TLS certificates for both RHV and OSP conv hosts
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsActions.test.js.snap
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsReducer.test.js.snap
  app/javascript/react/screens/App/Settings/helpers.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/ConversionHostWizardAuthenticationStep.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/ConversionHostWizardAuthenticationStep.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/index.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/index.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/__snapshots__/helpers.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/helpers.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/index.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/helpers.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/GeneralSettings.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/__snapshots__/GeneralSettings.test.js.snap
  app/javascript/react/screens/App/Settings/settings.fixtures.js
Labels: UI, bz, enhancement, ivanchuk/yes, v1.3

#1106 [BZ#1796200] Mapping Wizard: sort items alphabetically and allow horizontal scroll in item lists
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/DualPaneMapper/DualPaneMapper.scss
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/DualPaneMapper/DualPaneMapperList.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/DualPaneMapper/DualPaneMapperListItem.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/helpers.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardDatastoresStep/components/DatastoresStepForm/DatastoresStepForm.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/NetworksStepForm.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardNetworksStep/components/NetworksStepForm/helpers.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/helpers.js
Labels: UI, bz, changelog/yes, enhancement, ivanchuk/yes

#1104 Add tests for warm migration modal changes
  .jest-global-setup.js
  app/javascript/react/screens/App/Overview/__test__/OverviewActions.test.js
  app/javascript/react/screens/App/Overview/__test__/OverviewSelectors.test.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/CutoverTimeInfoItem.test.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/MigrationInProgressListItem.test.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/ScheduleMigrationButton.test.js
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/__snapshots__/CutoverTimeInfoItem.test.js.snap
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/__snapshots__/MigrationInProgressListItem.test.js.snap
  app/javascript/react/screens/App/Overview/components/Migrations/__test__/__snapshots__/ScheduleMigrationButton.test.js.snap
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/__test__/ScheduleMigrationModal.test.js
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/__test__/ScheduleMigrationModalBody.test.js
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/__test__/__snapshots__/ScheduleMigrationModal.test.js.snap
  app/javascript/react/screens/App/Overview/components/ScheduleMigrationModal/__test__/__snapshots__/ScheduleMigrationModalBody.test.js.snap
  app/javascript/react/screens/App/Overview/overview.transformationPlans.fixtures.js
  package.json
Labels: test

#1108 [#1069] [BZ#1775385] Mapping Wizard: Fix OSP conversion host check to be more strict
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStep.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepActions.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepConstants.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/MappingWizardClustersStep.test.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/ClustersStepForm.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/components/ClustersStepForm/__tests__/ClustersStepForm.test.js
Labels: UI, bug, bz, changelog/no, ivanchuk/yes

#1109 [Part 3/3 of BZ#1789479] UI changes for UCI: Remove OpenStack User field from conversion host wizard, always pass "cloud-user".
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/ConversionHostWizardAuthenticationStep.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/ConversionHostWizardAuthenticationStep.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/__snapshots__/helpers.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/helpers.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/helpers.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/index.js
Labels: UI, bz, enhancement, ivanchuk/yes, v1.3

#1112 [IVANCHUK] Backport for #1085 (UI changes for UCI: use VMs instead of Hosts for RHV conversion host configuration)
  app/javascript/common/constants.js
  app/javascript/react/screens/App/Mappings/screens/MappingWizard/components/MappingWizardClustersStep/MappingWizardClustersStepSelectors.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/ConversionHostWizardHostsStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/ConversionHostWizardHostsStep.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/__snapshots__/ConversionHostWizardHostsStep.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardHostsStep/__tests__/index.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/RetryConversionHostConfirmationModal.js
  app/javascript/react/screens/App/common/forms/TypeAheadSelectField.js
  app/javascript/redux/common/targetResources/targetResourcesConstants.js
Labels: UI, v1.3

#1113 [IVANCHUK] Backport for #1099 ([Part 2/3 of BZ#1789479] UI changes for UCI: disable CPU throttling, accept TLS certificates for both RHV and OSP conv hosts)
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsActions.test.js.snap
  app/javascript/react/screens/App/Settings/__tests__/__snapshots__/SettingsReducer.test.js.snap
  app/javascript/react/screens/App/Settings/helpers.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/ConversionHostWizardAuthenticationStep.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/ConversionHostWizardAuthenticationStep.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/index.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/index.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/index.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/__snapshots__/helpers.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/helpers.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/__tests__/index.test.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardResultsStep/helpers.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/GeneralSettings.js
  app/javascript/react/screens/App/Settings/screens/GeneralSettings/__tests__/__snapshots__/GeneralSettings.test.js.snap
  app/javascript/react/screens/App/Settings/settings.fixtures.js
Labels: UI, enhancement, v1.3

#1111 Remove react-intl & related code
  app/javascript/common/i18n.js
  app/javascript/common/i18nProviderWrapperFactory.js
  app/javascript/components/__mocks__/componentRegistry.js
  app/javascript/components/componentRegistry.js
  app/javascript/components/dates/IsoDate.js
  app/javascript/components/dates/IsoDate.test.js
  app/javascript/components/dates/LongDateTime.js
  app/javascript/components/dates/LongDateTime.test.js
  app/javascript/components/dates/RelativeDateTime.js
  app/javascript/components/dates/RelativeDateTime.test.js
  app/javascript/components/dates/ShortDateTime.js
  app/javascript/components/dates/ShortDateTime.test.js
  app/javascript/components/dates/__snapshots__/IsoDate.test.js.snap
  app/javascript/components/dates/__snapshots__/LongDateTime.test.js.snap
  app/javascript/components/dates/__snapshots__/RelativeDateTime.test.js.snap
  app/javascript/components/dates/__snapshots__/ShortDateTime.test.js.snap
  app/javascript/components/index.js
  package.json
Labels: technical debt

#1105 Update react-router-dom & connected-react-router
  app/javascript/react/config/Routes.js
  package.json
Labels: dependencies

#1110 Fix update of vertical menu styles after menu click
  app/javascript/common/menu.js
Labels: bug

#1115 [BZ#1807477] Replace info message for Conversion Host SSH Private Key field
  app/javascript/react/screens/App/Settings/SettingsConstants.js
  app/javascript/react/screens/App/Settings/__tests__/helpers.test.js
  app/javascript/react/screens/App/Settings/helpers.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/ConversionHostWizardAuthenticationStep.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardAuthenticationStep/__tests__/__snapshots__/ConversionHostWizardAuthenticationStep.test.js.snap
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/RetryConversionHostConfirmationModal.js
  app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/RetryConversionHostConfirmationModal/__tests__/__snapshots__/RetryConversionHostConfirmationModal.test.js.snap
Labels: UI, bug, bz, ivanchuk/yes, v1.3
