Repository ManageIQ/manageiq-v2v, pull requests merged in 2021-10, with the labels that each got.

#1158 Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472
  .travis.yml
Labels: test

#1159 Remove patternfly sass gems dependencies
  app/javascript/react/screens/App/App.scss
  app/javascript/react/screens/App/colors/colorVariables.scss
Labels: enhancement

#1160 Add missing color variables
  app/javascript/react/screens/App/colors/colorVariables.scss
Labels: bug
